- README.md
- package.json
- pnpm-lock.yaml
Addressed some minor issues to speed up things when setting the project up locally.
1. Added **turbo** as a dev dependency. Previously, I assume it was expected to be available globally but I didn't see it documented on the README file. Now, as a dev dependency, everything that's needed comes with `pnpm i`
2. Updated README to include running `pnpm run db:push` as a step. While trying out the project myself, I got an error on the API saying things didn't exist. After running the db command to sync the schemas, it worked like a charm.
> Fix local setup issues. Install turbo and new README step

- apps/web-app/pages/join/passkey.vue
removes duplicate exit button from passkey modal
before:
after:
Fixes #36
> feat(web-app): removes duplicate exit button from passkey modal

- .well-known/security.txt
- SECURITY.md
- apps/landing-page/public/.well.known/security.txt
- apps/web-app/public/.well-known/security.txt
Adding a security.txt file enables security researchers to quickly and easily see where they can submit security issues and know that they are being taken serious. From the proposal website:
"When security risks in web services are discovered by independent security researchers who understand the severity of the risk, they often lack the channels to disclose them properly. As a result, security issues may be left unreported. security.txt defines a standard to help organizations define the process for security researchers to disclose security vulnerabilities securely.”
See also https://securitytxt.org/
> chore: create security.txt

- apps/web-app/components/convos/convoList.vue
- apps/web-app/components/convos/convoMessages.vue
- apps/web-app/components/convos/sidebar.vue
- apps/web-app/components/settings/addNewEmail.vue
- apps/web-app/components/settings/addNewInvite.vue
- apps/web-app/components/settings/sidebar.vue
- apps/web-app/components/un/editor.vue
- apps/web-app/pages/[orgSlug]/convo/404.vue
- apps/web-app/pages/[orgSlug]/settings/org/mail/addresses/[emailIdentityId].vue
- apps/web-app/pages/[orgSlug]/settings/org/mail/addresses/index.vue
- apps/web-app/pages/[orgSlug]/settings/org/mail/domains/[domainId].vue
- apps/web-app/pages/[orgSlug]/settings/org/mail/domains/index.vue
- apps/web-app/pages/[orgSlug]/settings/org/setup/billing.vue
- apps/web-app/pages/[orgSlug]/settings/org/users/groups/[groupId].vue
- apps/web-app/pages/[orgSlug]/settings/org/users/groups/index.vue
- apps/web-app/pages/[orgSlug]/settings/org/users/invites/index.vue
- apps/web-app/pages/[orgSlug]/settings/org/users/members/index.vue
- apps/web-app/pages/join/secure.vue
Fixes #100
This PR fixes having scrollbar everywhere by making overflow auto. Its not a perfect solution as when scrollbar becomes visible, it shifts the content to the left. But it is better than having scrollbar everywhere.
In near future, we should consider using [Radix Scroll Area](https://www.radix-vue.com/components/scroll-area.html) or the shadcn version of that.
> fix(web): hide scrollbars by default

- packages/mailtools/src/prepareMessage.ts
- packages/mailtools/src/removeQuotations.ts
- packages/mailtools/src/removeStyles.ts
this adds 1 new function to the mail-parser to clean up and remove some specific style attributes
it also adds new ways to match signatures and quotes that should cover a much wider range of email providers
Fixes #116
> feat(mail-parser): improve signature/quote detection, add new style cleaner

- packages/mailtools/package.json
- packages/mailtools/playground/index.ts
- packages/mailtools/src/index.ts
- packages/mailtools/src/parseMessage.ts
- packages/mailtools/src/removeQuotations.ts
- packages/mailtools/src/removeSignatures.ts
- packages/mailtools/src/removeStyles.ts
- packages/mailtools/src/tests/prepareMessage/generateFixtureOutputs.ts
- packages/mailtools/src/tests/prepareMessage/prepareMessage.test.ts
- packages/mailtools/src/tests/prepareMessage/prepareMessageTestOptions.ts
- pnpm-lock.yaml
Fixes #120  #121 
This pr introduces a playground for local testing of the mailtools package
we have also split out the signature parser from the quotations parser
it now returns the parsed signatures in plain text and html
and the cleanstyles function can now accept an array of styles to remove, or if set to true will remove default styles
**NOT DONE:**
tests were not added for the new stuff...
> feat(mailtools): add playground, refactor signature extractions

- apps/platform/trpc/routers/authRouter/twoFactorRouter.ts
There was an issue where:
When creating account using password
if the user refreshes the screen before scanning the 2FA QR code
the system would think that 2FA is set up and not show the code again
this change checks if 2fa has been validated, if not, it creates a new code
> fix(auth): when setting up 2fa, ensure 2fa enabled on page refresh

- apps/mail-bridge/routes/postal/mail/inbound/[...mailServer].post.ts
- apps/platform/trpc/routers/convoRouter/entryRouter.ts
- apps/web-app/components/convos/convoMessageItem.vue
- packages/database/schema.ts
this PR adds functionality to store all incoming email's headers and html body
it then offers a way for users to view the raw email data in the ui
this opens up a modal to view the headers and orginal html body
Raw messages are given an expiry data, after which a cron job will delete the raw data to reduce DB usage
> feat(all): store raw incoming html emails and headers

- apps/web-app/components/settings/addNewDomain.vue
- apps/web-app/components/settings/addNewEmail.vue
- apps/web-app/components/settings/addNewGroup.vue
- apps/web-app/pages/[orgSlug]/settings/user/addresses.vue
- apps/web-app/stores/eeStore.ts
isPro checks on the frontend would sometimes return incorrect values, blocking the forms from displaying
this pr moves isPro to a pinaStore
> fix(web): isPro checks

- apps/mail-bridge/package.json
- apps/mail-bridge/smtp/auth.ts
- apps/mail-bridge/smtp/sendEmail.ts
- apps/mail-bridge/trpc/index.ts
- apps/mail-bridge/trpc/routers/sendMailRouter.ts
- apps/mail-bridge/trpc/routers/smtpRouter.ts
- packages/database/schema.ts
- pnpm-lock.yaml
Fixes #196
Adds support for using external SMTP servers as email identities.
Todo:
> feat: add mail-bridge functions and routes for external SMTP

- apps/platform/trpc/routers/authRouter/passkeyRouter.ts
- apps/platform/trpc/routers/authRouter/passwordRouter.ts
- apps/platform/trpc/routers/authRouter/twoFactorRouter.ts
- apps/platform/trpc/routers/userRouter/defaultsRouter.ts
- apps/platform/trpc/routers/userRouter/securityRouter.ts
- apps/platform/utils/auth/luciaDbAdaptor.ts
- apps/platform/utils/auth/passkeyDbAdaptor.ts
- apps/platform/utils/auth/passkeys.ts
- packages/database/schema.ts
move all auth stuff from `accountCredentials` to `accounts1 with out breaking anything
> feat: move everything to accounts table instead of credentials

- CONTRIBUTING.md
Clarifies default branch name in contributing.md
> docs: update name of default branch in contributing docs

- apps/web-app/components/un/ui-alert.vue
- apps/web-app/pages/[orgShortcode]/convo/new.vue
fixes the alert message when writing a new convo and not having an email identity assigned
> fix(web): no email sending identity alert

- apps/mail-bridge/middleware/verifyPostalSig.ts
- apps/storage/routes/attachment/[orgShortcode]/[attachmentId]/[filename].ts
- apps/web-app/layouts/home.vue
- apps/web-app/pages/[orgShortcode]/convo/[id].vue
Add error logs for postal signature middleware back
but dont allow to get past of it fails
> chore: add back postal signature verification failure logs

- apps/web-app/pages/[orgShortcode]/settings/user/security.vue
Make password and 2FA reset buttons work
> feat: add password and passkey reset buttons

- apps/web-app/components/convos/convoMessageItem.vue
handles when an email contains no text
fixes #266
> fix(web): handle body empty state

- packages/database/package.json
- pnpm-lock.yaml
New update to drizzle studio broke compatibility with installed kit. Updating `drizzle-kit` to `v0.20.15` fixes the issue.
FFS, why do they break things like this, and never mention that stuff is breaking.
> fix: resolve issues with drizzle studio by upgrading drizzle-kit

- apps/mail-bridge/package.json
- apps/storage/package.json
Uses `node` in start script instead of `tsx` directly
> fix: use node instead of tsx directly

- apps/mail-bridge/postal-routes/inbound.ts
Mailbridge email handler waited syncronously to process emails in the new version, it lead yo timeouts.
Now it returns response immediately and handles the email in backgorund
> fix: make email handler async and return response immediately to avoid timeout

- apps/platform/trpc/routers/convoRouter/convoRouter.ts
- apps/web/app/[orgShortCode]/Sidebar.tsx
- apps/web/app/[orgShortCode]/convo/ConvoList.tsx
- apps/web/hooks/use-loading.ts
1. The convo cursor now properly denotes the end of convos.
2. log out invalidates cache
fixes #421
> fix: properly handle end of convos cursor, invalidate cache on logout

- apps/web/src/app/[orgShortCode]/_components/sidebar.tsx
- apps/web/src/app/[orgShortCode]/convo/[convoId]/_components/chat-sidebar.tsx
- apps/web/src/app/[orgShortCode]/convo/[convoId]/page.tsx
- pnpm-lock.yaml
Show attachments in Convo Sidebar
Also fixes the issue when logging out, users see an unauthorized error
> feat: Convo attachments in Sidebar

- apps/web/src/app/[orgShortCode]/settings/user/security/_components/reset-modals.tsx
- apps/web/src/app/[orgShortCode]/settings/user/security/page.tsx
Recovery Section of Security Page
> feat: Recovery Setup/Disable Modal

- apps/platform/trpc/routers/userRouter/securityRouter.ts
- apps/web/src/app/[orgShortCode]/settings/user/security/_components/delete-modals.tsx
- apps/web/src/app/[orgShortCode]/settings/user/security/_components/passkey-modals.tsx
- apps/web/src/app/[orgShortCode]/settings/user/security/page.tsx
Passkeys Section of Security Page
> feat: Passkeys section to show/add/delete passkeys

- apps/web/src/app/[orgShortCode]/settings/user/security/_components/session-modals.tsx
- apps/web/src/app/[orgShortCode]/settings/user/security/page.tsx
Last part of secutrity page, sessions
fixes #440
> feat: sessions section with logout one/all sessions

- apps/mail-bridge/postal-routes/inbound.ts
- apps/mail-bridge/utils/contactParsing.ts
Fixes #477
This PR changes the flow of email address parsing to fix the issue when if the receiver was previously a contact they don't get parsed as proper email identity.
This is a hotfix, once this PR is merged to main, it will also be applied to production.
> hotfix: changes contact parser flow to fix bugs with already existing contacts

- ee/apps/billing/middlewares.ts
Use non-parsed body for stripe middleware signature checking
> fix: use raw body for stripe webhook parsing

- apps/platform/trpc/routers/convoRouter/convoRouter.ts
- apps/web/package.json
- apps/web/src/app/[orgShortCode]/_components/sidebar.tsx
- apps/web/src/app/[orgShortCode]/convo/[convoId]/_components/messages-panel.tsx
- apps/web/src/app/[orgShortCode]/convo/[convoId]/_components/participants.tsx
- apps/web/src/app/[orgShortCode]/convo/[convoId]/_components/reply-box.tsx
- apps/web/src/app/[orgShortCode]/convo/[convoId]/_components/top-bar.tsx
- apps/web/src/app/[orgShortCode]/convo/[convoId]/page.tsx
- apps/web/src/app/[orgShortCode]/convo/layout.tsx
- apps/web/src/app/[orgShortCode]/convo/utils.ts
- apps/web/src/app/layout.tsx
- apps/web/src/components/avatar.tsx
- apps/web/src/components/shadcn-ui/button.tsx
- apps/web/src/components/shadcn-ui/drawer.tsx
- apps/web/src/components/shadcn-ui/select.tsx
- apps/web/src/components/shared/attachments.tsx
- apps/web/src/components/shared/editor.tsx
- apps/web/src/hooks/is-mobile.ts
- apps/web/src/lib/utils.ts
- apps/web/src/providers/realtime-provider.tsx
- apps/web/src/styles/globals.css
- packages/tiptap/extensions.ts
- pnpm-lock.yaml
Adds the convo view panel according to new designs
> feat(web): Convo View

- packages/realtime/client.ts
Now that we have realtime properly working on dev server, allow both `ws` and `wss` protocol to allow using stagging realtime on local dev.
> fix: allow `ws`/`wss` protocol for realtime client

- apps/mail-bridge/package.json
- apps/mail-bridge/queue/mail-processor/worker.ts
- pnpm-lock.yaml
Mail Bridge will now generate more informative file name for missing file names for attachments.
> fix: file name generation for missing filenames for attachments

- .env.local.example
- apps/platform/env.ts
- apps/platform/trpc/routers/authRouter/passkeyRouter.ts
- apps/platform/trpc/routers/authRouter/passwordRouter.ts
- apps/platform/trpc/routers/authRouter/recoveryRouter.ts
- apps/platform/trpc/trpc.ts
- apps/web/package.json
- apps/web/src/app/(login)/_components/passkey-login.tsx
- apps/web/src/app/(login)/login/page.tsx
- apps/web/src/app/join/secure/_components/modals.tsx
- apps/web/src/app/join/secure/page.tsx
- apps/web/src/app/recovery/page.tsx
- apps/web/src/components/turnstile.tsx
- pnpm-lock.yaml
Adds turnstile on sign in/up and recovery pages. It is not problematic like we had in the Nuxt version.
Not setting the `TURNSTILE_SECRET_KEY` and `NEXT_PUBLIC_TURNSTILE_SITE_KEY` variables will disable it on platfrom and web respectively. Both needs to be either enabled or disabled for it to work.
> feat: add turnstile to sign in, sign up, and recovery pages

- apps/web/src/app/[orgShortCode]/convo/[convoId]/page-client.tsx
- apps/web/src/app/[orgShortCode]/convo/[convoId]/page.tsx
- apps/web/src/app/[orgShortCode]/convo/new/page.tsx
Hi everyone! This PR adds document titles and metadata to each page in the convo route indicating information about the `page/convo`. I closed the first PR to make it more focused, since applying this logic in the `settings` path would have implied too many changes. If this one is merged, I can open another one for the `settings` routes using the same logic.
Fixes https://github.com/un/inbox/issues/215
> feat(next): add metadata to convo pages

- apps/platform/trpc/routers/convoRouter/convoRouter.ts
- apps/platform/trpc/routers/orgRouter/mail/emailIdentityRouter.ts
- apps/web/src/app/[orgShortCode]/convo/[convoId]/_components/reply-box.tsx
- apps/web/src/app/[orgShortCode]/convo/_components/create-convo-form.tsx
- apps/web/src/components/shadcn-ui/tooltip.tsx
When a email is created with a domain that is not yet verified, disable sending emails form that domain.
On frontend show a tooltip that the email identity is disabled. on platform add checks to throw error if provided email identity is disabled
> feat: disable sending emails from unverified email identities

- .env.local.example
- apps/web/next.config.js
- apps/web/package.json
- apps/web/src/app/[orgShortCode]/_components/sidebar-content.tsx
- apps/web/src/app/[orgShortCode]/convo/[convoId]/page-client.tsx
- apps/web/src/app/[orgShortCode]/settings/org/users/invites/_components/columns.tsx
- apps/web/src/components/shared/attachment-button.tsx
- apps/web/src/components/shared/attachments.tsx
- apps/web/src/components/turnstile.tsx
- apps/web/src/env.js
- apps/web/src/lib/trpc.tsx
- apps/web/src/lib/utils.ts
- apps/web/src/providers/realtime-provider.tsx
- pnpm-lock.yaml
Web app env is now typesafe and we dont need to define `NEXT_PUBLIC_` prefixed env anymore. We can expose selected env variables.
> feat: web app env is now type safe and auto prefixed

- apps/web/next.config.js
- apps/web/package.json
This PR is trying to make Next.js work with standalone build outputs.
This feature provides better and faster performance while running in Docker containers.
There are caveats that this doesn't work properly with monorepos out of the box. So some trickery has to be done to get it working with out setup.
According to my tests on local machine it works exactly as normal nextjs builds work. But It was noticeably faster.
We will try this mode in Staging for some time and If it doesn't break, we will continue to use it. Otherwise we will need to revert this PR.
> feat: experimental standalone build mode

- apps/platform/routes/auth.ts
- apps/web/src/app/[orgShortCode]/convo/[convoId]/_components/convo-views.tsx
- apps/web/src/app/[orgShortCode]/convo/[convoId]/page.tsx
- apps/web/src/hooks/use-page-title.tsx
- apps/web/src/lib/middleware-utils.ts
- apps/web/src/middleware.ts
Removed the server side trpc api and changed the redirect call to a plain fetch call to make the middleware function small, efficient and reliable.
> feat: improve middleware performance by using plain fetch calls

- apps/web/package.json
- apps/web/src/lib/middleware-utils.ts
Fixes the random TLS issues found in web middleware only found in deployments.
> fix: web middleware fetch TLS issues

- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/participants.tsx
Added the `cursor-pointer` class to a `div` element in the `Participants` component to enhance user interactivity.
A `div` within the `Participants` component now includes the `cursor-pointer` class. This change makes the element more visibly interactive to users by changing the cursor to a pointer when hovered over.
1. Navigate to a conversation page that displays the participants list.
2. Hover over the participants' names.
3. Observe if the cursor changes to a pointer.
The change improves the UI/UX by giving users a visual indication that the element is interactive, which aligns with standard web practices.
---
> fix: add pointer cursor to participant panel trigger

- apps/platform/trpc/routers/authRouter/passwordRouter.ts
- apps/platform/trpc/routers/authRouter/recoveryRouter.ts
- apps/platform/trpc/routers/orgRouter/mail/emailIdentityRouter.ts
- packages/utils/zodSchemas.ts
Sets username validation to only allow letters and numbers
removed previously added `. - _` due to issues
it allows login with those characters since we have 200 users with those characters in their names
---
> fix: username validation regex

- apps/web/src/components/shadcn-ui/input-otp.tsx
- apps/web/tailwind.config.ts
Adds the cursor blink animation in Input OTP
> fix: input otp cursor blink animation

- apps/web/src/app/[orgShortcode]/_components/claim-email-identity.tsx
Fix the sizing of buttons in Email Claim modal
> fix: email identity claim modal button sizes

- apps/platform/trpc/routers/orgRouter/users/invitesRouter.ts
Ensure the `inviteUrl` no longer includes the protocol `https://`.
Removed the `https://` protocol prefix from the `inviteUrl` when generating a new invite link.
1. Generate a new invite link.
2. Verify that the generated invite URL does not include the `https://` prefix.
This change ensures better flexibility when resolving URLs based on different contexts or environments, avoiding hard-coded protocols.
---
> fix(inviteUrl): remove unnecessary protocol from url

- apps/web/src/app/[orgShortcode]/layout.tsx
The app will now automatically retry if the org layout fails to load and will give users a button to reload the page
> chore: improve app layout with auto reties and manual retry buttons

- apps/platform/trpc/routers/convoRouter/convoRouter.ts
- apps/web/package.json
- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/top-bar.tsx
- apps/web/src/app/[orgShortcode]/convo/_components/convo-list-item.tsx
- apps/web/src/app/[orgShortcode]/convo/_components/convo-list.tsx
- apps/web/src/app/[orgShortcode]/convo/_components/delete-convos-modal.tsx
- apps/web/src/app/[orgShortcode]/convo/atoms.ts
- apps/web/src/app/[orgShortcode]/convo/layout.tsx
- apps/web/src/app/[orgShortcode]/convo/utils.ts
- apps/web/src/components/shadcn-ui/context-menu.tsx
- packages/realtime/events.ts
- pnpm-lock.yaml
> feat: Multiple select hide/unhide and delete

- apps/web/src/providers/realtime-provider.tsx
- packages/realtime/client.ts
Realtime client tries to open 2 web socket connection everytime. This PR fixes that by not disconnecting the older one if its not yet connected so a second one doesn't occur
> fix: realtime client opening 2 connections

- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/reply-box.tsx
- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/top-bar.tsx
Sends selected email identity along with the reply mutation for replying to external emails. Also added the loading on delete modal.
This fixes the issue of replying to external emails.
You can test this PR with `pnpm dev:r`, you need two accounts and need to have 2 emails which are not linked to same org. Now you can start a convo between those 2 emails and reply back-forth. If it works its fine.
> fix: replying to convo with email identity works now

- apps/web/package.json
- apps/web/src/app/[orgShortcode]/_components/sidebar-content.tsx
- apps/web/src/app/[orgShortcode]/convo/_components/create-convo-form.tsx
- apps/web/src/app/[orgShortcode]/convo/new/page.tsx
- pnpm-lock.yaml
This PR adds support for pre-filling email recipients and subject when creating a new conversation via URL parameters. It also updates the "Support" link in the sidebar to open a new conversation with the support email pre-filled.
- Updated `CreateConvoForm` component to accept `initialEmails` and `initialSubject` props
- Modified the new conversation page to parse `emails` and `subject` query parameters
- Updated the "Support" link in the sidebar to include pre-filled email and subject
- Minor package updates (nuqs)
1. Click the "Support" link in the sidebar and verify it opens a new conversation with support@uninbox.com pre-filled
2. Test creating a new conversation with custom email and subject via URL: 
`/[orgShortcode]/convo/new?emails=test@example.com&subject=Test Subject` …
> feat: ability to send a message to support

- apps/platform/trpc/routers/orgRouter/users/invitesRouter.ts
- ee/apps/billing/routes/stripe.ts
- ee/apps/billing/trpc/routers/subscriptionsRouter.ts
I found a few bugs in the redeemInvite logic while investigating the issue with stripe billing, this PR fixes this.
- Type of `totalOrgMember` was string, casted to number
- Always return a response from stripe webhook endpoint
- Throw error if user tries to join same org again
> fix: bugs I found in redeem invite logic

- apps/web/src/app/[orgShortcode]/settings/org/users/invites/_components/columns.tsx
- apps/web/src/app/[orgShortcode]/settings/org/users/invites/page.tsx
- apps/web/src/app/[orgShortcode]/settings/user/addresses/page.tsx
Some settings page were not consistently full width, specially invites table looked awful.
This PR makes every settings page follow same general layout
> chore: make every settings page consistently full width

- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/messages-panel.tsx
- apps/web/src/styles/globals.css
Replace `nbsp` with normal spaces and hide transparent colored elements to make them non selectable.
All done on client side to be able to revert back later
> chore: fix some issues with email messages on client

- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/messages-panel.tsx
Remove `&shy;` in client side html
> fix: remove `&shy;` tags from message content

- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/messages-panel.tsx
Bandage fix for the app crash when messageAuthor is not found in participants.
We need to add something to record these scenarios and find the root cause. I can't find the root cause until I can reproduce the issue myself.
> fix: bypass the message author undefined crash

- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/convo-views.tsx
- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/messages-panel.tsx
- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/reply-box.tsx
- apps/web/src/app/[orgShortcode]/convo/[convoId]/atoms.ts
Automatically select the identity associated with the convo
> fix: automatically select correct email identity when replying

- apps/platform/storage.ts
We had redis TTL using `ms(...)` while it takes seconds as argument, which made everything last 1000x longer, now they use `seconds(...)` which fixes the issue
FIxes ENG-132
> chore: fix TTL for redis from ms to seconds

- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/reply-box.tsx
- apps/web/src/app/[orgShortcode]/convo/_components/create-convo-form.tsx
- apps/web/src/app/[orgShortcode]/convo/_components/new-convo-sheet.tsx
- apps/web/src/components/shadcn-ui/input.tsx
Various Improvements to convo and reply box
- There is a clear draft button now
- New Email participants now show up at front for easier un-selecting
- Email participants now loads correctly from draft
- New convo popup can be full screened now
- You can't select yourself as participant anymore, it was disabled but pressing it still added yourself
> feat: Improvements to convo and reply box

- apps/mail-bridge/package.json
- apps/mail-bridge/queue/mail-processor.ts
- apps/mail-bridge/smtp/sendEmail.ts
- apps/mail-bridge/trpc/routers/sendMailRouter.ts
- apps/mail-bridge/utils/tiptap-utils.ts
- apps/platform/ctx.ts
- apps/platform/trpc/routers/convoRouter/convoRouter.ts
- apps/platform/utils/tiptap-utils.ts
- apps/storage/app.ts
- apps/storage/ctx.ts
- apps/storage/middlewares.ts
- apps/storage/proxy/attachment.ts
- apps/storage/proxy/inline-proxy.ts
- apps/storage/storage.ts
- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/messages-panel.tsx
- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/reply-box.tsx
- apps/web/src/app/[orgShortcode]/convo/_components/create-convo-form.tsx
- apps/web/src/components/editor/index.tsx
- apps/web/src/hooks/use-inline-uploader.ts
- packages/tiptap/extensions/image-uploader.ts
- packages/tiptap/extensions/index.ts
- packages/tiptap/package.json
- packages/tiptap/react.ts
- pnpm-lock.yaml
Fixes #680 
- Emails are now sent as raw emails to postal so that we can support inline attachments and use convoId and convo entryId as custom Message-Id
- Inline Images are supported via pendingAttachment table and inline-proxy api, while submitting the convo the urls are replaced with correct attachments in platform and `cid` with attached inlined attachments
- extra changes, functions and hooks to support inline images
As there are core changes we need to test everything with sending emails, receiving emails, etc
> feat: raw emails and inline images support

- apps/web/src/app/[orgShortcode]/convo/_components/create-convo-form.tsx
Fix the stupid error when instead of checking if editor has anything, I checked if editor was empty
> fix: empty editor checker

- apps/web/src/app/[orgShortcode]/layout.tsx
- apps/web/src/components/shadcn-ui/alert-dialog.tsx
- apps/web/src/components/shadcn-ui/dialog.tsx
- Hide bottom nav on mobile while a convo is open to get more screen space
- Make dialogs left aligned on mobile too, as that looks better
> fix: hide bottom nav in convo and fix dialog text alignment

- apps/web/src/app/[orgShortcode]/convo/layout.tsx
While using the old `/org/convo/c_xxxxx` format the app crashes due to a space not being available. This makes it fallback to `all`
> fix: app crash while using old url format for convos

- ee/apps/billing/trpc/routers/iCanHazRouter.ts
fixes https://linear.app/unn/issue/ENG-154/when-creating-space-worflows-cant-add-more-even-if-pro-plan
> fix:allows workflows on pro plan

- apps/platform/trpc/routers/convoRouter/convoRouter.ts
- apps/platform/trpc/routers/spaceRouter/spaceRouter.ts
- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/top-bar.tsx
- apps/web/src/app/[orgShortcode]/layout.tsx
- packages/realtime/events.ts
- Update caches while moving/adding convo to spaces
- Update workflow statues with realtime for syncing b/w every org member
Fixes ENG-150
Fixes ENG-151
> feat: Update convos moving b/w spaces, sync workflow with realtime

- apps/web/src/app/[orgShortcode]/settings/org/users/invites/_components/invite-modal.tsx
Resolves: #707  
In the Invite Modal, when an organization has no domains, the "Create Email Address" option is now disabled. This prevents users from trying to create an email address when it's not possible.
A tooltip is added to explain the limitation, informing users that they need to add a domain first to enable this option. This approach improves the user experience by preventing confusion and guiding them effectively.
Fixes #707 
- [ ✔️] Bug fix (non-breaking change which fixes an issue)
- [ ✔️] Enhancement (small improvements)
- [ ✔️] Read [Contributing Guide](https://github.com/un/inbox/blob/main/CONTRIBUTING.md)
- [ ✔️] Self-reviewed my own code
- [✔️ ] Tested my code in a local environment
- [ ✔️] Commented on my code in hard-to-understand areas
- [ ✔️] Checked for warnings, …
> [Invite Modal] Disables "Select/Create Email Address" if no domains :black_heart:

- apps/web/src/app/[orgShortcode]/convo/_components/convo-list-item.tsx
Fixes the word breaking for convo previews
Before:
After:
> fix: random ellipsis in convo previews

- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/convo-views.tsx
When a convo is received in a space own participant id is not defined, it breaks styling while replying to unassigned convos.
This PR revalidates cache on reply if the id is not defined, fixing the issue
Fixes ENG-157
> fix: update convo participants cache when replying to a unassigned convo

- apps/mail-bridge/package.json
- apps/mail-bridge/scripts/email-templates.ts
- apps/mail-bridge/scripts/mock-incoming.ts
- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/convo-views.tsx
- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/messages-panel.tsx
- package.json
- pnpm-lock.yaml
- Added a script to easily mock incoming postal emails
- Fix the reply rendering issue which stayed in #727
> fix: add mock incoming email script and fix the reply formatting bug

- apps/web/src/components/avatar-plus.tsx
Don't show hover card when there are no extra participants in avatar plus hover card
> fix: don't show avatar plus hover card if there are no other users

- apps/web/src/app/[orgShortcode]/convo/utils.ts
When multiple convos are selected, deleting a single convo doesn't remove that convo from selection list which leads to error while deleting all others in multi select.
So we remove the deleted convos from selection.
> fix: remove convo from selection if deleted

- apps/mail-bridge/queue/mail-processor.ts
- apps/mail-bridge/scripts/mock-incoming.ts
Make incoming email mock use file path for raw emails
> fix: use files in mock-incoming

- apps/web/src/app/[orgShortcode]/settings/org/mail/addresses/add/page.tsx
Fix form schema to allow smtp port to be a number coerced from string.
> fix: form schema for smtp port

- apps/mail-bridge/trpc/routers/sendMailRouter.ts
- apps/platform/trpc/routers/orgRouter/mail/emailIdentityRouter.ts
- apps/web/src/app/[orgShortcode]/convo/_components/create-convo-form.tsx
- Send emails in proper format while sending over external SMTP
- Fix `org.mail.emailIdentities.getUserEmailIdentities` endpoint while `spaceShortcode` is `personal`
- Automatically translate own space to `personal` and vice versa
> feat: fix emails while sending with external credentials

- apps/web/src/app/[orgShortcode]/convo/_components/create-convo-form.tsx
- apps/web/src/app/[orgShortcode]/convo/utils.ts
Updates the correct space cache when creating a new convo
Fixes ENG-164
> fix: Update correct space when creating a convo

- apps/worker/env.ts
- apps/worker/functions/check-dns.ts
- packages/utils/dns/verifier.ts
The DNS check updates records everytime as SPF check in worker was invalid. This fixes the check for spf.
> fix: worker DNS check for SPF

- apps/mail-bridge/postal-db/functions.ts
- apps/platform/utils/updateDnsRecords.ts
- apps/worker/services/dns-check-queue.ts
Disable domain if the domain has expired (`NXDOMAIN`) and skip their DNS check with worker.
Fixes ENG-121
> feat: disable domain if DNS records not found (NXDOMAIN)

- apps/mail-bridge/queue/mail-processor.ts
- packages/database/index.ts
- packages/otel/helpers.ts
- packages/otel/setup.ts
Some improvements to OpenTelemetry system
> chore: improvements to OTEL system

- apps/platform/trpc/routers/convoRouter/convoRouter.ts
- apps/storage/proxy/attachment.ts
Fixes ENG-166
Inline images now work even if they have special characters in their names
also fixed the bug where replying with attachments were sent marked as inline so users could not see them
> fix: inline images breaking due to special characters

- apps/platform/trpc/routers/orgRouter/setup/billingRouter.ts
- apps/platform/trpc/routers/userRouter/securityRouter.ts
- apps/web/package.json
- apps/web/src/app/[orgShortcode]/settings/org/setup/billing/_components/plans-table.tsx
- apps/web/src/app/[orgShortcode]/settings/org/setup/billing/page.tsx
- apps/web/src/env.ts
- ee/apps/billing/app.ts
- ee/apps/billing/routes/stripe.ts
- ee/apps/billing/scripts/sync-stripe-db.ts
- ee/apps/billing/trpc/routers/stripeLinksRouter.ts
- ee/apps/billing/trpc/routers/subscriptionsRouter.ts
- pnpm-lock.yaml
Fixes ENG-111
Fixes ENG-126
Fixes ENG-116
Fixes #476
- Subscribing to Plans are now done in a embedded Checkout modal without having user to leave UnInbox.
- Handle subscription creation, updates and deletes properly
- Update subscription details when a user deletes their account
- Create a migration script for syncing stripe with `orgBiliing` database
- Change the metadata to only store `orgId` and `totalusers`, as everything else should be determined by stripe price objects
- We need a new Env variable with name `BILLING_STRIPE_PUBLISHABLE_KEY` to render the stripe modal
> feat: billing system overhaul

- apps/web/src/app/[orgShortcode]/convo/_components/create-convo-form.tsx
Fixes #709
So if you disable the add participant then the email identity drop box hides itself. Howsoever I have still handled it. Also I wanna ask if there exist no email identity then should be disable the entire form rather than just the participant.
> fix(new-convo): empty email identity handled

- apps/mail-bridge/package.json
- apps/mail-bridge/smtp/sendEmail.ts
- apps/mail-bridge/trpc/routers/sendMailRouter.ts
- pnpm-lock.yaml
replacing `mimetext` with nodemailer's `mail-composer` as it seems to be better in terms of following the rfc
> feat: migrate from mimetext to mail-composer for raw emails

- apps/platform/trpc/routers/orgRouter/setup/billingRouter.ts
- apps/platform/trpc/routers/userRouter/securityRouter.ts
- apps/web/package.json
- apps/web/src/app/[orgShortcode]/settings/org/setup/billing/_components/plans-table.tsx
- apps/web/src/app/[orgShortcode]/settings/org/setup/billing/page.tsx
- apps/web/src/env.ts
- ee/apps/billing/app.ts
- ee/apps/billing/routes/stripe.ts
- ee/apps/billing/scripts/sync-stripe-db.ts
- ee/apps/billing/trpc/routers/stripeLinksRouter.ts
- ee/apps/billing/trpc/routers/subscriptionsRouter.ts
- pnpm-lock.yaml
This PR is a duplicate of #751, which was reverted due to incompatibility which the setup
This is a draft currently, and we need to discuss changes before we can merge it again
> feat: billing system changes

- apps/platform/trpc/routers/orgRouter/iCanHaz/iCanHazRouter.ts
- apps/platform/trpc/routers/orgRouter/setup/billingRouter.ts
- apps/web/src/app/[orgShortcode]/settings/_components/settings-sidebar.tsx
- apps/web/src/app/[orgShortcode]/settings/org/setup/billing/page.tsx
- apps/web/src/app/[orgShortcode]/settings/user/addresses/page.tsx
- ee/apps/billing/trpc/routers/iCanHazRouter.ts
Don't show billing related stuff if billing is not available
> fix: settings billing issues for selfhosted

- apps/platform/trpc/routers/convoRouter/convoRouter.ts
- apps/storage/proxy/attachment.ts
- apps/storage/proxy/avatars.ts
- apps/storage/proxy/inline-proxy.ts
- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/messages-panel.tsx
- apps/web/src/components/editor/index.tsx
- packages/tiptap/extensions/index.ts
Add Cache headers to storage to cache avatar and attachments on user's browser
> chore: add cache headers to storage proxies

- apps/platform/utils/auth/passkeyUtils.ts
- ee/apps/command/src/server/trpc/routers/accountRouter.ts
- packages/database/migrations/0001_flimsy_mercury.sql
- packages/database/migrations/meta/0001_snapshot.json
- packages/database/migrations/meta/_journal.json
- packages/database/schema.ts
Remove `accountCredential` table and `preAccount` columns
Remember to run `pnpm db:migrate`
> chore: remove unused db stuff

- apps/web/package.json
- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/messages-panel.tsx
- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/reply-box.tsx
- apps/web/src/app/[orgShortcode]/convo/_components/convo-list-item.tsx
- apps/web/src/app/[orgShortcode]/convo/_components/create-convo-form.tsx
- apps/web/src/app/[orgShortcode]/layout.tsx
- apps/web/src/app/[orgShortcode]/settings/user/security/_components/password-modals.tsx
- apps/web/src/app/[orgShortcode]/tunnels.ts
- apps/web/src/app/join/org/_components/create-org.tsx
- apps/web/src/app/join/page.tsx
- apps/web/src/app/join/secure/_components/secure-cards.tsx
- apps/web/src/app/recovery/reset-password/reset/page.tsx
- apps/web/src/components/copy-button.tsx
- apps/web/src/lib/utils.ts
- pnpm-lock.yaml
- Remove `@uidotdev/usehooks` and `tunnel-rat`
- Migrate `useDebouce` to use `use-debounce` package
- Add `use-long-press` which works better than the generic hook from `@uidotdev/usehooks`
- Replace `useCopyToClipboard` for a normal function
> chore: clean up for unused deps and replacements for deps

- apps/platform/trpc/routers/spaceRouter/spaceRouter.ts
- apps/platform/trpc/routers/spaceRouter/spaceSettingsRouter.ts
- apps/web/src/app/[orgShortcode]/[spaceShortcode]/settings/page.tsx
- apps/web/src/app/[orgShortcode]/_components/sidebar-content.tsx
- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/reply-box.tsx
- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/top-bar.tsx
- apps/web/src/app/[orgShortcode]/convo/_components/convo-list-base.tsx
- apps/web/src/app/[orgShortcode]/convo/_components/convo-list-item.tsx
- apps/web/src/app/[orgShortcode]/convo/_components/convo-list.tsx
- apps/web/src/app/[orgShortcode]/convo/_components/create-convo-form.tsx
- apps/web/src/app/[orgShortcode]/convo/_components/delete-convos-modal.tsx
- apps/web/src/app/[orgShortcode]/convo/layout.tsx
- apps/web/src/hooks/use-params.ts
- Make `useSpaceShortcode` return `string | null` by default, by passing `true` as argument to the hook we can throw if code is not defined and narrow down the type to `string`
- Spaces show settings button if the use can access settings page
- Extra clean up and improvements to space settings page
> fix: show settings based on permissions and spaceShortcode hook cleanup

- ee/apps/billing/routes/stripe.ts
- ee/apps/billing/scripts/sync-stripe-db.ts
Delete subscription from db only if the event is a delete event to prevent out of order events from deleting db entires
> fix: delete subscription only if the event is a delete event

- apps/mail-bridge/queue/mail-processor.ts
Handle adding participents when the from address is a email identity
> fix: handle form emails being identities

- apps/platform/trpc/routers/spaceRouter/spaceSettingsRouter.ts
- apps/platform/trpc/routers/spaceRouter/utils.ts
- apps/web/src/app/[orgShortcode]/[spaceShortcode]/settings/page.tsx
Fixes ENG-140
Personal spaces can always be made private regardless of pro plan
Once affected spaces are private again, we don't allow to open them to avoid confusion
> fix: personal spaces can be made private without a pro plan

- apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/messages-panel.tsx
- apps/web/src/app/[orgShortcode]/convo/_components/convo-list-item.tsx
- apps/web/src/components/smart-date-time.tsx
`SmartDateTime` shows relative time for the specified time, it has a tooltip which shows the real date and time. after the specified time it shows the date only. Time still being accessable in the tooltip
> chore: add smart date time component with tooltip
