CONTRIBUTING.md, SUPPORT.md
This pull request updates / adds the contributing guidelines and support documentation to provide more comprehensive and clear instructions for contributors and users.
•	Added sections on asking questions, opening an issue, and submitting pull requests
•	Updated the bug report and feature request guidelines
•	Clarified the process for triaging issues and contributing code
•	Added Support and Contributing .md's.
•	Added a support section with information on seeking help through Stack Overflow and Discord
These updates will improve the onboarding experience for new contributors and users, ensuring that they have the necessary information to contribute or seek help effectively. The changes align with the project's guidelines for documentation and maintain consistency with the existing coding …
=> Added Contributing Guidelines and Support Documentation

apps/web-app/server/trpc/routers/authRouter.ts, apps/web-app/server/trpc/routers/orgRouter/orgCrudRouter.ts, apps/web-app/server/trpc/routers/orgRouter/setup/billingRouter.ts, apps/web-app/server/trpc/routers/userRouter/profileRouter.ts, apps/web-app/server/trpc/trpc.ts
Infers TRPC ctx.user exists after calling userProcedure
=> feat: infer user as always true after authed proc

apps/web-app/components/settings/addNewDomain.vue, apps/web-app/components/settings/addNewEmail.vue, apps/web-app/components/settings/addNewGroup.vue, apps/web-app/components/settings/addNewInvite.vue, apps/web-app/pages/[orgSlug]/convo/new.vue, apps/web-app/pages/[orgSlug]/settings/org/index.vue, apps/web-app/pages/[orgSlug]/settings/org/new.vue, apps/web-app/pages/[orgSlug]/settings/user/addresses.vue, apps/web-app/pages/[orgSlug]/settings/user/profiles.vue, apps/web-app/pages/join/index.vue, apps/web-app/pages/join/org.vue, apps/web-app/pages/join/passkey.vue, apps/web-app/pages/join/profile.vue
Added the trim() function to zod validation
Fixed #13
=> Fixed Zod Validation #13

apps/web-app/components/settings/addNewGroup.vue
Sorry for late PR 
Fixed issue #9 
If any fix required let me know :smiley: 
**CURRENTLY `pnpm build:web-app` is FALLING**
=> feat/fix(#9): when creating group, add create new email option

apps/mail-bridge/trpc/routers/domainRouter.ts, apps/mail-bridge/trpc/routers/orgRouter.ts, apps/web-app/server/trpc/routers/convoRouter/messageRouter.ts, apps/web-app/server/trpc/routers/orgRouter/mail/domainsRouter.ts, apps/web-app/server/trpc/routers/orgRouter/mail/emailIdentityRouter.ts, apps/web-app/server/trpc/routers/orgRouter/setup/profileRouter.ts, apps/web-app/server/trpc/routers/orgRouter/users/groupsRouter.ts, apps/web-app/server/trpc/routers/orgRouter/users/invitesRouter.ts, apps/web-app/server/trpc/routers/userRouter/profileRouter.ts, packages/utils/index.ts, packages/utils/package.json
I havent tested this worked and just used github.dev - but here is what i mean 
(From discord DMs)
=> chore: extract nano id zod schema to a reusable util

apps/web-app/components/layout/navbar.vue
This works around a suspense bug (likely) in vue, or in Nuxt.
Fixes https://github.com/uninbox/UnInbox/issues/23
=> fix: use lazy loading of account to workaround suspense bug

apps/web-app/components/settings/domainDnsItem.vue, apps/web-app/pages/[orgSlug]/settings/org/mail/domains/[domainId].vue
Fixes #17
Modifies the Accordian component with the UAccordian component from Nuxt-ui
=> update domainDetails page to use NuxtUi Accordion component

apps/mail-bridge/trpc/routers/domainRouter.ts, apps/web-app/server/trpc/routers/orgRouter/mail/domainsRouter.ts, packages/postal-puppet/src/index.ts, packages/postal-puppet/src/puppets/domainRefreshDns.ts
Fixes https://github.com/uninbox/UnInbox/issues/27
=> fix(mailbridge): recheck postal dns when checking domain dns

apps/web-app/components/layout/navbar.vue, apps/web-app/pages/index.vue, apps/web-app/pages/redirect.vue
Fixes #29 
Also fixes the logout button not working properly. Improved the login flow in general
=> fix(web-app): improve login and failure messages

apps/web-app/server/trpc/routers/orgRouter/orgCrudRouter.ts
=> new profile created when user joins new org

apps/web-app/app/spa-loading-template.html, apps/web-app/layouts/convos.vue, apps/web-app/layouts/settings.vue, apps/web-app/middleware/auth.global.ts, apps/web-app/nuxt.config.ts, apps/web-app/pages/index.vue, apps/web-app/pages/join/index.vue, apps/web-app/pages/join/invite/[inviteId].vue, apps/web-app/pages/join/passkey.vue, apps/web-app/server/api/auth/status.get.ts
This sets the app to use a hybrid rendering strategy
the "logged out" user pages load via SSR
once logged in, a user enters SPA mode where all rendering is done client side
this is the initial implementation, but some route based optimizations will need to occur (data loading states)
=> ✨ feat(web): switch to SPA mode for app

apps/web-app/components/un/ui-avatar.vue, apps/web-app/composables/utils.ts
Fixes # https://github.com/uninbox/UnInbox/issues/52
=> refactor(web): 🎨 refactor UnUiAvatar component + url

apps/web-app/components/un/ui-avatar.vue, apps/web-app/pages/[orgSlug]/settings/org/mail/addresses/[emailIdentityId].vue, apps/web-app/pages/[orgSlug]/settings/org/mail/domains/[domainId].vue, apps/web-app/pages/[orgSlug]/settings/org/users/groups/[groupId].vue
=> fix(web): fix back arrow links and remove debug info

apps/landing-page/components/Header.vue
=> fix(landing): Navigational Header scroll #64

apps/landing-page/pages/index.vue
=> fix(landin): remove additional FAQ q

apps/landing-page/pages/index.vue
This PR is to update index.vue to fix issue `#73` ([Minor grammatical mistakes on landing FAQs](https://github.com/uninbox/UnInbox/issues/73)).
Please review and merge. Thanks.
=> docs(landing): Fix FAQ Grammar

apps/landing-page/pages/index.vue
Adds a Question for data residency to the FAQ
Fixes # (issue) n/a
- [x ] Read [Contributing Guide](./CONTRIBUTING.md)
- [ x] Self-reviewed my own code
- [ x] Tested my code in a local environment
- [ x] Commented on my code in hard-to-understand areas
- [ x] Checked for warnings, there are none
- [ x] Removed all `console.logs`
- [ x] Merged the latest changes from main onto my branch with `git pull origin main`
- [ x] My changes don't cause any responsiveness issues
=> docs(landing): FAQ - add data residency question

.github/pull_request_template.md
Fixes the contributing.md to be absolute.
=> chore: fix contributing.md link in pull request template

packages/mailtools/package.json, packages/mailtools/src/appendStyle.ts, packages/mailtools/src/blockRemoteContent/blockRemoteContentInAttributes.ts, packages/mailtools/src/blockRemoteContent/blockRemoteContentInStyle.ts, packages/mailtools/src/blockRemoteContent/index.ts, packages/mailtools/src/cheerio-utils.ts, packages/mailtools/src/enforceViewport.ts, packages/mailtools/src/fixBrokenHtml.ts, packages/mailtools/src/linkify.ts, packages/mailtools/src/parseMessage.ts, packages/mailtools/src/removeTrailingWhitespace.ts, packages/mailtools/src/tests/appendStyle.test.ts, packages/mailtools/src/tests/enforceViewport.test.ts, packages/mailtools/src/tests/linkify.test.ts, packages/mailtools/src/tests/remoteContent/blockRemoteContent.test.ts, packages/mailtools/src/tests/removeQuotationsSignatures.test.ts, packages/mailtools/src/tests/removeTrailingWhitespaces.test.ts, packages/mailtools/src/tests/walkBackwards.test.ts, packages/mailtools/src/walkBackwards.ts, packages/mailtools/tsup.config.ts, packages/mailtools/vitest.config.ts, pnpm-lock.yaml
Adds more tracking Urls to the tracking list, but regex based ones are not added yet due to complexity.
ref: #119
Also fixes the test that broke while breaking up quote and signature detection into separate functions.
=> feat(mailtools): add more tracking url and fix tests

apps/mail-bridge/routes/postal/mail/inbound/[...mailServer].post.ts, apps/mail-bridge/trpc/routers/sendMailRouter.ts, apps/platform/trpc/routers/convoRouter/convoRouter.ts, apps/storage/api/attachments/mailfetch.post.ts, apps/storage/api/attachments/presign.get.ts, apps/web-app/components/convos/upload.vue, apps/web-app/composables/types.ts, apps/web-app/pages/[orgSlug]/convo/new.vue, packages/database/schema.ts
This PR enables sending new messages with attachments included
max file size for uploads in one email is 15mb
- [X If a UI change was made: Added a screen recording or screenshots to this PR
=> feat(platform) Send emails with attachments

apps/platform/trpc/routers/convoRouter/convoRouter.ts
=> fix(platform) sending cc email

apps/web-app/app.config.ts, apps/web-app/app.vue, apps/web-app/components/convos/convoList.vue, apps/web-app/components/convos/convoListItem.vue, apps/web-app/components/layout/navbar.vue, apps/web-app/components/settings/domainDnsItem.vue, apps/web-app/components/settings/sidebar.vue, apps/web-app/components/un/ui-avatar-plus.vue, apps/web-app/components/un/ui-avatar.vue, apps/web-app/layouts/home.vue, apps/web-app/package.json, apps/web-app/pages/[orgSlug]/convo.vue, apps/web-app/pages/[orgSlug]/convo/[id].vue, apps/web-app/pages/[orgSlug]/settings.vue, apps/web-app/pages/[orgSlug]/settings/org/mail/domains/[domainId].vue, apps/web-app/pages/index.vue, apps/web-app/tailwind.config.ts, pnpm-lock.yaml
This PR updates styling across the webapp to use Radix colors
we've also removed some stylistic choices and cleaned up other random parts of the app
=> feat(web): update ui + radix colors

apps/web-app/app.config.ts, apps/web-app/app/spa-loading-template.html, apps/web-app/components/layout/navbar.vue, apps/web-app/components/settings/sidebar.vue, apps/web-app/components/un/ui-input.vue, apps/web-app/pages/[orgSlug]/settings/org/setup/billing.vue, apps/web-app/pages/join/2fa.vue, apps/web-app/pages/join/index.vue, apps/web-app/pages/join/org.vue, apps/web-app/pages/join/profile.vue, apps/web-app/pages/join/secure.vue
Fixes broken stylings across the app
=> fix(web): styling

package.json, pnpm-lock.yaml
=> chore: update turborepo

package.json
=> chore: remove test command

.vscode/cspell.json, apps/mail-bridge/routes/postal/mail/inbound/[...mailServer].post.ts, apps/platform/realtime.ts, apps/platform/routes/realtime/auth.post.ts, apps/platform/trpc/routers/convoRouter/convoRouter.ts, apps/platform/trpc/routers/convoRouter/entryRouter.ts, apps/platform/utils/realtime.ts, apps/storage/api/avatar.post.ts, apps/web-app/components/convos/convoList.vue, apps/web-app/components/convos/convoMessages.vue, apps/web-app/composables/types.ts, apps/web-app/layouts/home.vue, apps/web-app/pages/[orgSlug]/convo/[id].vue, apps/web-app/stores/convoEntryStore.ts, apps/web-app/stores/convoStore.ts, packages/realtime/client.ts, packages/realtime/server.ts, packages/utils/typeId/index.ts
This PR adds realtime updates to sending and receiving of internal and external messages
=> feat(all): send and receive with realtime updates

.husky/pre-commit, .prettierignore, package.json, pnpm-lock.yaml
Setup auto formatting before commits using git hooks (husky, lint-staged) to avoid CI failing due to a silly formatting issue, test/lint would not be added in git hooks as they take significant time to execute, so they would be run on CI only.
=> chore: setup formatting with git-hooks

apps/web-app/components/layout/navbar.vue, apps/web-app/pages/index.vue, apps/web-app/pages/join/2fa.vue, apps/web-app/pages/join/index.vue, apps/web-app/pages/join/invite/[inviteId].vue, apps/web-app/pages/join/org.vue, apps/web-app/pages/join/profile.vue, apps/web-app/pages/join/secure.vue
=> feat(web): add "beta" badges

packages/tiptap/extensions.ts, packages/tiptap/package.json, pnpm-lock.yaml
=> feat(web): add tiptap inline images

apps/platform/trpc/routers/userRouter/defaultsRouter.ts, apps/web-app/components/layout/navbar.vue, apps/web-app/components/settings/sidebar.vue
=> fix(web): settings page un-split

package.json
Make git hooks format changed files only
=> chore: improve formatter performance by formatting staged files only

apps/platform/trpc/routers/authRouter/passwordRouter.ts, apps/platform/trpc/trpc.ts, apps/web-app/pages/index.vue, apps/web-app/pages/join/index.vue, apps/web-app/pages/join/invite/[inviteId].vue, apps/web-app/pages/join/secure.vue, packages/utils/password/index.ts
This PR turns the public turnstile captchas into automatic invisible captchas.
Please note that the type of captcha is controlled by cloudflare control panel and is not controlled on the client. the client now assumes the captcha is invisible and works with that assumption.
There were also some big fixes related to this, and few missing schemas are now standardized.
Also fixes #207
=> feat: invisible Turnstile captcha and some improvements

apps/platform/trpc/index.ts, apps/platform/trpc/routers/authRouter/passkeyRouter.ts, apps/platform/trpc/routers/authRouter/passwordRouter.ts, apps/platform/trpc/routers/userRouter/securityRouter.ts, apps/platform/trpc/trpc.ts, apps/platform/utils/auth/luciaDbAdaptor.ts, apps/platform/utils/auth/passkeyDbAdaptor.ts, apps/platform/utils/auth/passkeys.ts, apps/web-app/components/settings/security/passwordReset.vue, apps/web-app/components/settings/security/totpReset.vue, apps/web-app/components/settings/security/totpSetup.vue, apps/web-app/components/settings/sidebar.vue, apps/web-app/pages/[orgSlug]/settings/user/security.vue, apps/web-app/pages/index.vue, apps/web-app/pages/join/index.vue, apps/web-app/pages/join/invite/[inviteId].vue, apps/web-app/pages/join/secure.vue, apps/web-app/plugins/trpcClient.ts, packages/database/schema.ts, packages/utils/password/index.ts, packages/utils/typeId/index.ts
=> feat(web): security page

.vscode/cspell.json, apps/mail-bridge/trpc/routers/sendMailRouter.ts, apps/mail-bridge/trpc/routers/smtpRouter.ts, apps/platform/trpc/routers/orgRouter/mail/emailIdentityExternalRouter.ts, apps/platform/trpc/routers/orgRouter/mail/emailIdentityRouter.ts, apps/platform/trpc/routers/orgRouter/users/invitesRouter.ts, apps/platform/trpc/routers/userRouter/addressRouter.ts, apps/web-app/app.config.ts, apps/web-app/components/settings/addNewEmailExternal.vue, apps/web-app/components/un/ui-input-menu.vue, apps/web-app/components/un/ui-input.vue, apps/web-app/pages/[orgSlug]/settings/org/mail/addresses/index.vue, packages/database/schema.ts, packages/utils/typeId/index.ts
this feature allows adding and sending emails via an external email identity based on SMTP
=> feat(web): add External Email Identity

apps/web-app/components/convos/convoMessageItem.vue, apps/web-app/components/convos/sidebar.vue, apps/web-app/components/layout/navbar.vue, apps/web-app/components/settings/addTotp.vue, apps/web-app/components/settings/sidebar.vue, apps/web-app/composables/utils.ts, apps/web-app/layouts/home.vue, apps/web-app/pages/[orgSlug]/convo.vue, apps/web-app/pages/[orgSlug]/convo/[id].vue, apps/web-app/pages/[orgSlug]/settings.vue, apps/web-app/pages/[orgSlug]/settings/org/users/members/index.vue, apps/web-app/pages/[orgSlug]/settings/user/security.vue, apps/web-app/pages/index.vue, apps/web-app/pages/join/org.vue, apps/web-app/pages/join/profile.vue, apps/web-app/pages/join/secure.vue, apps/web-app/stores/convoStore.ts, pnpm-lock.yaml
=> feat(web): mobile view

apps/web-app/components/convos/convoMessageItem.vue, apps/web-app/components/layout/navbar.vue, apps/web-app/composables/utils.ts, apps/web-app/pages/[orgSlug]/convo/[id].vue, apps/web-app/pages/[orgSlug]/convo/new.vue
enables posting a comment on new convos and replies
=> feat(web): post comment

apps/web-app/pages/[orgSlug]/settings.vue
=> fix(web): settings page overlap

packages/custom-mariadb/Dockerfile, packages/custom-mariadb/config
=> chore: add custom mariadb docker image

packages/database/migrate.ts, packages/database/migrations/0000_first_payback.sql, packages/database/migrations/meta/0000_snapshot.json, packages/database/migrations/meta/_journal.json, packages/database/package.json
=> feat(db): initial migration

packages/custom-mariadb/Dockerfile, packages/custom-mariadb/config
Reverts un/inbox#223
moved to separate repo
=> Revert "chore: add custom mariadb docker image"

apps/platform/trpc/routers/authRouter/passkeyRouter.ts, apps/web-app/pages/join/secure.vue
=> fix(web): passkey signup error

apps/web-app/pages/join/index.vue, apps/web-app/pages/join/secure.vue
=> fix: another day, another turnstile issue

apps/web-app/layouts/home.vue, packages/realtime/client.ts
=> fix: disable wss with soketi, don't block UI on realtime connection failure

apps/platform/trpc/routers/orgRouter/users/invitesRouter.ts
=> fix invite link

package.json
=> fix billing build

apps/web-app/pages/[orgShortcode]/convo/new.vue
=> disable draft button

apps/web-app/pages/[orgShortcode]/settings/org/setup/billing.vue
=> fix iing page link

apps/web-app/pages/join/index.vue
=> add signup terms and conditions

README.md
=> chore: update readme to mention public beta launch

apps/mail-bridge/middleware/verifyPostalSig.ts, apps/mail-bridge/routes/postal/mail/inbound/[...mailServer].post.ts, apps/storage/api/attachments/internalPresign.post.ts, apps/storage/middleware/01.cors.ts, apps/storage/nitro.config.ts
Fixes a few things and adds log to storage and mail-bridge
=> chore: fix a few things with mail-bridge and storage

apps/web-app/nuxt.config.ts, apps/web-app/pages/[orgShortcode]/convo/new.vue, apps/web-app/pages/index.vue, apps/web-app/pages/join/2fa.vue, apps/web-app/pages/join/org.vue, apps/web-app/pages/join/profile.vue, apps/web-app/pages/join/secure.vue, apps/web-app/pages/unboarding/index.vue
=> minor fixes

README.md, apps/web-app/components/layout/navbar.vue, apps/web-app/pages/eu.vue, apps/web-app/pages/index.vue, apps/web-app/pages/join/2fa.vue, apps/web-app/pages/join/index.vue, apps/web-app/pages/join/invite/[inviteId].vue, apps/web-app/pages/join/org.vue, apps/web-app/pages/join/profile.vue, apps/web-app/pages/join/secure.vue
=> remove beta, we are now sigma

apps/web-app/components/convos/sidebar.vue
=> potential mobile new convo fix

apps/mail-bridge/package.json, pnpm-lock.yaml
Bump `@u22n/mailtools` to latest version
=> chore: bump @u22n/mailtools to v0.1.1

apps/web-app/pages/[orgShortcode]/settings/org/users/members/index.vue
Hi UnInbox.
:black_heart:
Updates button in header of members to match other setting pages.
Before:
After:
For comparison, another settings page:
Fixes #255 
Looking into CONTRIBUTING.md there is a line:
```
**Update the CHANGELOG** for all enhancements and bug fixes. Include the corresponding issue number if one exists, and your GitHub username. (example: "- Fixed crash in profile view. #123 @jessesquires")
```
However I cannot find CHANGELOG file in project. Any path to file apprecieated.
Also I would welcome suggestion for a next thing to work on.
=> fix: use UnUiButton in members settings header

apps/platform/trpc/routers/orgRouter/orgCrudRouter.ts, apps/web-app/pages/[orgShortcode]/settings/org/new.vue, apps/web-app/pages/join/org.vue
=> chore: improve org short code error message

apps/mail-bridge/middleware/verifyPostalSig.ts
=> chore(mail-bridge): remove postal webhook logs

apps/web-app/layouts/home.vue, apps/web-app/package.json, packages/realtime/client.ts, pnpm-lock.yaml
=> fix(web): UI is not blocked if realtime connection fails

apps/mail-bridge/trpc/routers/domainRouter.ts, apps/platform/trpc/routers/userRouter/securityRouter.ts, apps/platform/utils/auth/passkeys.ts, apps/web-app/composables/utils.ts, apps/web-app/pages/[orgShortcode]/settings/user/security.vue, apps/web-app/pages/join/secure.vue
fixes bug where arc only saves passkeys to local browser and not system
=> fix(web): arc browser passkey install

apps/mail-bridge/package.json, pnpm-lock.yaml
Bumps `@u22n/mailtools` to `v0.1.2`
=> chore(mail-bridge): bump @u22n/mailtools to v0.1.2

apps/web-app/components/settings/sidebar.vue, apps/web-app/pages/[orgShortcode]/settings.vue, apps/web-app/pages/[orgShortcode]/settings/index.vue, apps/web-app/pages/[orgShortcode]/settings/org/index.vue, apps/web-app/pages/[orgShortcode]/settings/org/mail/addresses/[emailIdentityId].vue, apps/web-app/pages/[orgShortcode]/settings/org/mail/addresses/index.vue, apps/web-app/pages/[orgShortcode]/settings/org/mail/domains/[domainId].vue, apps/web-app/pages/[orgShortcode]/settings/org/mail/domains/index.vue, apps/web-app/pages/[orgShortcode]/settings/org/new.vue, apps/web-app/pages/[orgShortcode]/settings/org/setup/billing.vue, apps/web-app/pages/[orgShortcode]/settings/org/users/groups/[groupId].vue, apps/web-app/pages/[orgShortcode]/settings/org/users/groups/index.vue, apps/web-app/pages/[orgShortcode]/settings/org/users/invites/index.vue, apps/web-app/pages/[orgShortcode]/settings/org/users/members/index.vue, apps/web-app/pages/[orgShortcode]/settings/user/addresses.vue, apps/web-app/pages/[orgShortcode]/settings/user/profiles.vue, apps/web-app/pages/[orgShortcode]/settings/user/security.vue
fixes the mobile settings UI to be separate page as per convos
=> fix(web): setting menu ui

apps/web-app/pages/[orgShortcode]/convo/[id].vue, apps/web-app/pages/[orgShortcode]/convo/new.vue
fixes uploading and removing attachments in new convos and replies
=> fix(web): attachment uploads and removals

apps/platform/trpc/routers/userRouter/addressRouter.ts, apps/web-app/pages/[orgShortcode]/settings/user/addresses.vue
allows copying the forwardingEmailAddress for personal email identities
=> fix(web): personal forwarding address ui

apps/web-app/components/layout/mobile-nav.vue, apps/web-app/layouts/home.vue
changes the nav bar for mobile to just be two buttons
=> fix(web): mobile nav bar

apps/platform/trpc/routers/userRouter/defaultsRouter.ts
a potential fix for when a user dosnt have an org and results in endless redirect loop
=> fix(web): possible redirect with no org fix

apps/platform/trpc/routers/orgRouter/users/invitesRouter.ts, apps/web-app/pages/join/invite/[inviteId].vue
fixes when an existing user opens an invite, allows to join org with existing account
=> fix(web): invite with existing user

apps/web-app/components/settings/addNewDomain.vue, apps/web-app/components/settings/addNewEmail.vue, apps/web-app/components/settings/addNewEmailExternal.vue, apps/web-app/components/settings/addNewGroup.vue, apps/web-app/components/settings/addNewInvite.vue, apps/web-app/pages/[orgShortcode]/settings/org/new.vue, apps/web-app/pages/[orgShortcode]/settings/user/addresses.vue, apps/web-app/pages/join/invite/[inviteId].vue, apps/web-app/pages/join/profile.vue
removes stupid redirect timeouts on several "new" functions
=> fix(web): remove random redirects timeouts

apps/platform/trpc/routers/orgRouter/mail/emailIdentityRouter.ts, apps/web-app/layouts/home.vue
when user logs in, or refreshes app, we check if they have an email identity, if they dont, we show modal to claim email address.
they can dismiss, and it will show again when they login/refresh
=> feat(web): if no email identity, offer to claim

apps/platform/trpc/routers/authRouter/passwordRouter.ts, apps/platform/trpc/routers/authRouter/signupRouter.ts, apps/platform/trpc/routers/userRouter/securityRouter.ts, packages/utils/index.ts, packages/utils/package.json, packages/utils/password/index.ts, pnpm-lock.yaml
=> feat(platform): add haveIBeenPwned password check

apps/web-app/components/un/editor.vue, apps/web-app/pages/[orgShortcode]/convo/[id].vue, apps/web-app/pages/[orgShortcode]/convo/new.vue, packages/tiptap/package.json, packages/tiptap/vue.ts, pnpm-lock.yaml
=> feat: fix tiptap, attachments overflow and stuff

.vscode/cspell.json, apps/mail-bridge/routes/postal/mail/inbound/[...mailServer].post.ts, packages/database/schema.ts
Fixes #265
More testing is needed before merge
=> feat(mail-bridge): handle inline attachments properly

apps/mail-bridge/postal-db/index.ts, apps/mail-bridge/routes/postal/mail/inbound/[...mailServer].post.ts, apps/platform/middleware/01.cors.ts, apps/platform/nitro.config.ts, apps/platform/trpc/routers/convoRouter/convoRouter.ts, apps/storage/middleware/01.cors.ts, apps/storage/nitro.config.ts, apps/storage/routes/attachment/[orgShortcode]/[attachmentId]/[filename].ts, apps/web-app/pages/[orgShortcode]/convo/[id].vue, apps/web-app/pages/redirect.vue, packages/tiptap/extensions.ts
Merges back staging only fixes to main branch
- Handle attachment uploads and replacing them with uploaded Url Properly
- CORS issues with Storage and Platfrom
- Filter out inline attachments in UI
- Fixes Postal DB disconnect issue
- Fixes rediect loop which happens if username cookie expires
Need to update database schema before merging to `production`
=> feat(staging): Merge staging fixes back to main (1)

apps/platform/trpc/routers/convoRouter/convoRouter.ts, apps/web-app/components/un/editor.vue, apps/web-app/pages/[orgShortcode]/convo/[id].vue
=> fix(web): editor reset upon reply

apps/web-app/app.config.ts, apps/web-app/app.vue
=> feat(web): add "live on product hunt banner"

ee/apps/billing/trpc/routers/subscriptionsRouter.ts
fixes billing issue where dosnt update stripe seats count
=> fix(billing): update org sub count

.vscode/cspell.json, apps/platform/trpc/routers/userRouter/addressRouter.ts, apps/web-app/pages/[orgShortcode]/settings/user/addresses.vue, ee/apps/command/pages/index.vue, ee/apps/command/pages/unin.vue, ee/apps/command/server/trpc/index.ts, ee/apps/command/server/trpc/routers/accountRouter.ts, packages/database/schema.ts
adds capability to assign and redeem our signup bonuses for @unin.me email addresses
=> 🚑 fix(all): launch bonuses

apps/platform/trpc/routers/authRouter/passwordRouter.ts, apps/platform/trpc/routers/userRouter/securityRouter.ts, apps/web-app/components/settings/security/passwordReset.vue, apps/web-app/components/settings/security/recoveryCode.vue, apps/web-app/components/settings/security/totpReset.vue, apps/web-app/pages/[orgShortcode]/settings/user/security.vue, apps/web-app/pages/index.vue
Fixes #244 
With more UI and backend changes
*Needs more clean up in future*
=> feat(all): new auth router and page

.gitignore, apps/web-app/app.config.ts, apps/web-app/components/convos/convoListItem.vue, apps/web-app/components/convos/convoMessageItem.vue, apps/web-app/components/layout/navbar.vue, apps/web-app/components/un/ui-popover.vue
=> enhancement(web): message actions dropdown, ph link

apps/web-app/components/un/editor.vue
=> fix(web-app): Fix rounded borders in message editor

apps/platform/trpc/routers/authRouter/twoFactorRouter.ts, apps/web-app/pages/[orgShortcode]/settings/user/security.vue
Fixes a few bugs with the new Auth router
=> fix: a few auth router bugs

apps/web-app/pages/[orgShortcode]/convo/[id].vue
=> fix(web): convo reply: show send via email address dropdown

apps/platform/trpc/routers/orgRouter/mail/emailIdentityExternalRouter.ts, apps/platform/trpc/routers/orgRouter/mail/emailIdentityRouter.ts
=> fix(platform): BE/FE send name min length mismatch

apps/web-app/app.config.ts
=> fix(web): context panel BG in dark mode

apps/platform/trpc/routers/userRouter/defaultsRouter.ts, apps/web-app/pages/[orgShortcode]/index.vue, apps/web-app/pages/[orgShortcode]/settings/user/security.vue, apps/web-app/pages/index.vue, apps/web-app/pages/join/2fa.vue, apps/web-app/pages/join/org.vue, apps/web-app/pages/join/profile.vue, apps/web-app/pages/join/secure.vue, apps/web-app/pages/redirect.vue
This PR fixes if the user bypasses 2FA setup during onboarding
or if their 2FA is incorrectly configured
Redirecting them to the New Org onboarding if they do not have an org, or to their security page if they are an org member
=> fix(web): redirect if 2FA error

apps/web-app/pages/[orgShortcode]/settings/org/users/groups/index.vue
=> fix(web): group when no members shows [] instead of text

apps/web-app/components/convos/convoMessageItem.vue
=> fix(web): editor overflow on long text

apps/web-app/components/un/editor.vue
=> fix(web) Editor long text overflow scroll issue

apps/web-app/pages/[orgShortcode]/convo/[id].vue
=> fix(web): subject overflow on mobile

apps/web-app/layouts/home.vue, apps/web-app/pages/[orgShortcode]/convo/[convoId].vue
=> fix(web): new attachment in convo does not show

apps/web-app/components/convos/upload.vue, apps/web-app/layouts/home.vue, apps/web-app/pages/[orgShortcode]/convo/[convoId].vue, apps/web-app/pages/[orgShortcode]/convo/new.vue
=> fix(web):attachment upload limit

apps/mail-bridge/utils/realtime.ts, apps/platform/trpc/routers/convoRouter/convoRouter.ts, apps/platform/utils/realtime.ts, apps/web-app/components/convos/convoListItem.vue, apps/web-app/components/convos/hiddenConvoList.vue, apps/web-app/components/convos/sidebar.vue, apps/web-app/components/layout/navbar.vue, apps/web-app/layouts/home.vue, apps/web-app/pages/[orgShortcode]/convo/[convoId].vue, apps/web-app/stores/convoHiddenStore.ts, apps/web-app/stores/convoStore.ts, packages/database/migrations/0003_damp_callisto.sql, packages/database/migrations/meta/0003_snapshot.json, packages/database/migrations/meta/_journal.json, packages/database/schema.ts, packages/realtime/events.ts
Adds ability to hide conversations
convos are moved to a dedicated "hidden convos" list
when a new message comes in on a hidden convo, we unhide it
demo video here: https://twitter.com/UnInbox/status/1779954894239113683 or here: https://discord.com/channels/1113119653246545961/1118233720256737340/1229512521958821930
=> feat(all): Hide Convo

apps/platform/trpc/index.ts, apps/platform/trpc/routers/authRouter/passwordRouter.ts, apps/platform/trpc/routers/authRouter/recoveryRouter.ts, apps/platform/trpc/routers/userRouter/securityRouter.ts, apps/platform/trpc/trpc.ts, apps/platform/utils/auth/passkeys.ts, apps/web-app/pages/[orgShortcode]/index.vue, apps/web-app/pages/[orgShortcode]/settings/user/security.vue, apps/web-app/pages/index.vue, apps/web-app/pages/recovery.vue, apps/web-app/pages/redirect.vue
=> feat: create Recovery page and functionality

apps/web-app/pages/[orgShortcode]/settings/org/setup/billing.vue
these changes should have been included in a previous PR
not sure why they never made it
=> fix(billing): stripe refresh

packages/database/migrations/0004_last_firedrake.sql, packages/database/migrations/meta/0004_snapshot.json, packages/database/migrations/meta/_journal.json, packages/database/schema.ts
Fixes #316
Before deploying this we need to make sure that there changes doesn't drop any data and can be safely applied to production before deploying
=> fix: make raw html and public key columns bigger

apps/web-app/pages/[orgShortcode]/convo/index.vue
adds a button to view hidden messages on mobile
=> fix(web): mobile show hidden convo view

apps/platform/trpc/routers/convoRouter/convoRouter.ts, apps/platform/trpc/routers/userRouter/defaultsRouter.ts, apps/platform/utils/auth/passkeys.ts, apps/storage/api/attachments/deleteAttachments.post.ts, apps/web-app/layouts/home.vue, apps/web-app/pages/[orgShortcode]/convo/404.vue, apps/web-app/pages/[orgShortcode]/convo/[convoId].vue, apps/web-app/pages/[orgShortcode]/settings/org/setup/billing.vue, apps/web-app/plugins/trpcClient.ts, apps/web-app/stores/convoEntryStore.ts, apps/web-app/stores/convoHiddenStore.ts, apps/web-app/stores/convoStore.ts, ee/apps/command/server/trpc/routers/accountRouter.ts, packages/realtime/events.ts
This adds the capability to delete a conversation
the button is located in the convo actions bar
when first clicked it will prompt the user if they actually want to delete the convo since it will delete for all the participants.
we give the option to hide it instead.
=> feature(UN): Delete Convo

apps/platform/trpc/routers/orgRouter/users/membersRouter.ts, apps/web-app/components/settings/sidebar.vue, apps/web-app/pages/[orgShortcode]/settings/org/index.vue, apps/web-app/pages/[orgShortcode]/settings/org/mail/addresses/[emailIdentityId].vue, apps/web-app/pages/[orgShortcode]/settings/org/mail/addresses/index.vue, apps/web-app/pages/[orgShortcode]/settings/org/mail/domains/[domainId].vue, apps/web-app/pages/[orgShortcode]/settings/org/mail/domains/index.vue, apps/web-app/pages/[orgShortcode]/settings/org/setup/billing.vue, apps/web-app/pages/[orgShortcode]/settings/org/users/groups/[groupId].vue, apps/web-app/pages/[orgShortcode]/settings/org/users/groups/index.vue, apps/web-app/pages/[orgShortcode]/settings/org/users/invites/index.vue, apps/web-app/pages/[orgShortcode]/settings/org/users/members/index.vue
=> fix(web): only admins can access org settings

apps/platform/trpc/routers/orgRouter/mail/domainsRouter.ts, apps/web-app/pages/[orgShortcode]/settings/org/mail/domains/[domainId].vue
=> fix(web): domain dns shows "Unverified"

apps/web-app/components/convos/convoMessageItem.vue
:black_heart: 
This Fixes #355, comments should be able to be differentiated from Norma Emails. 
They are now displayed in a light / more dark blue color and black text which is not close to the actual conversation.
=> fix(web): Conversation comments should appear differently than messages

apps/web-app/components/convos/convoMessageItem.vue, apps/web-app/pages/[orgShortcode]/settings/user/security.vue
=> fix(web): Unable to delete passkeys even with legacy password enabled

.github/workflows/check_and_build_pull_requests.yaml, README.md, apps/web-app/package.json, ee/apps/command/package.json, package.json, pnpm-lock.yaml
Move Project and pnpm lock file to version 9
> This breaks compaitablity with older pnpm versions
=> chore: move workspace to pnpm@9

apps/web/app/[orgShortCode]/settings/user/addresses/claim-address-modal.tsx, apps/web/app/[orgShortCode]/settings/user/addresses/page.tsx, apps/web/app/[orgShortCode]/settings/user/profile/page.tsx, apps/web/app/[orgShortCode]/settings/user/security/PasswordModal.tsx, apps/web/app/[orgShortCode]/settings/user/security/VerificationModal.tsx, apps/web/app/[orgShortCode]/settings/user/security/page.tsx, apps/web/app/join/profile/ProfileCard.tsx, apps/web/app/join/profile/avatar-modal.tsx, apps/web/app/join/secure/modals.tsx, apps/web/app/join/secure/page.tsx, apps/web/hooks/use-awaitable-modal.ts
makes the `useAwaitableModal` hook better in DX
=> chore: better awaitable modal api

apps/mail-bridge/postal-routes/inbound.ts
=> fix(mail): resolve forwarding email errors

ee/apps/billing/trpc/routers/stripeLinksRouter.ts
=> fix(billing): allow promo codes

apps/web-app/pages/[orgShortCode]/convo/[convoId].vue
=> Fix: errors when deleting convo

apps/platform/trpc/routers/convoRouter/convoRouter.ts
=> handle deleting convo by team member

apps/web-app/pages/[orgShortCode]/convo/[convoId].vue
=> fix(web-nuxt): error when replying with no email identity

apps/web/app/[orgShortCode]/convo/ConvoList.tsx, apps/web/app/[orgShortCode]/convo/[convoId]/ChatSideBar.tsx, apps/web/app/[orgShortCode]/convo/[convoId]/page.tsx, apps/web/app/[orgShortCode]/convo/utils.ts
Support for Hiding and Unhiding Convo based on its previous status.
=> feat: Support for Hide/Unhide convo, with smart ConvoList updates

apps/web-app/pages/[orgShortCode]/convo/[convoId].vue, apps/web-app/pages/[orgShortCode]/convo/new.vue
hotfix for upload component
props broke with renaming of orgShortcode > orgShortCode
=> fix(web): :ambulance: hotfix - upload component props

apps/mail-bridge/app.ts, apps/platform/app.ts, apps/platform/trpc/routers/convoRouter/convoRouter.ts, apps/storage/app.ts, apps/web/package.json, apps/web/src/app/[orgShortCode]/convo/[convoId]/_components/chat-sidebar.tsx, apps/web/src/app/[orgShortCode]/convo/[convoId]/page.tsx, apps/web/src/app/[orgShortCode]/convo/new/editor.tsx, apps/web/src/app/[orgShortCode]/convo/new/page.tsx, apps/web/src/app/[orgShortCode]/convo/page.tsx, apps/web/src/app/[orgShortCode]/convo/utils.ts, apps/web/tailwind.config.ts, pnpm-lock.yaml
Message Reply Widgets
Ref #412
=> feat: Convo reply widgets

apps/platform/storage.ts
=> fix: use `sessions` as the key for platform which was wrong

ee/apps/billing/package.json, packages/realtime/client.ts
Added `Content-Type` header to fix the issue with realtime auth.
Also fixed billing app's issue
=> fix: add Content-Type header to realtime auth request

.vscode/cspell.json, apps/web/package.json, apps/web/src/app/[orgShortCode]/_components/atoms.ts, apps/web/src/app/[orgShortCode]/_components/sidebar-content.tsx, apps/web/src/app/[orgShortCode]/_components/sidebar-nav-button.tsx, apps/web/src/app/[orgShortCode]/_components/sidebar.tsx, apps/web/src/app/[orgShortCode]/convo/[convoId]/_components/context-panel.tsx, apps/web/src/app/[orgShortCode]/convo/[convoId]/_components/messages-panel.tsx, apps/web/src/app/[orgShortCode]/convo/_components/convo-list.tsx, apps/web/src/app/[orgShortCode]/convo/layout.tsx, apps/web/src/app/[orgShortCode]/layout.tsx, apps/web/src/app/layout.tsx, apps/web/src/components/shadcn-ui/avatar.tsx, apps/web/src/components/shadcn-ui/button.tsx, apps/web/src/components/shadcn-ui/dropdown-menu.tsx, apps/web/src/components/shadcn-ui/toggle-group.tsx, apps/web/src/components/shadcn-ui/toggle.tsx, apps/web/src/hooks/is-mobile.ts, apps/web/src/stores/preferences-store.ts, pnpm-lock.yaml
add new (auto collapsing) sidebar based up updated designs
=> feat(web): new sidebar

apps/mail-bridge/app.ts, apps/platform/app.ts, apps/storage/app.ts, ee/apps/billing/app.ts
=> feat: Handle errors in hono apps to prevent crashes

apps/web/src/app/[orgShortCode]/convo/_components/convo-list.tsx, apps/web/src/app/[orgShortCode]/convo/utils.ts
Convo List can now be toggled to show either the hidden or the non hidden convos.
Hiding/UnHiding convos will updates the lists
=> feat: Hide/Unhide convos with updating lists

apps/platform/trpc/routers/orgRouter/users/teamsRouter.ts, apps/web/src/app/[orgShortCode]/settings/org/users/invites/_components/invite-modal.tsx, apps/web/src/app/[orgShortCode]/settings/org/users/teams/[teamId]/_components/add-new-member.tsx, apps/web/src/app/[orgShortCode]/settings/org/users/teams/[teamId]/_components/columns.tsx, apps/web/src/app/[orgShortCode]/settings/org/users/teams/[teamId]/_components/member-editor.tsx, apps/web/src/app/[orgShortCode]/settings/org/users/teams/[teamId]/page.tsx, apps/web/src/app/[orgShortCode]/settings/org/users/teams/_components/columns.tsx, apps/web/src/app/[orgShortCode]/settings/org/users/teams/_components/new-team-modal.tsx, apps/web/src/app/[orgShortCode]/settings/org/users/teams/page.tsx, apps/web/src/components/shared/multiselect.tsx, apps/web/src/components/shared/table.tsx
All of the teams stuff
Add new teams
Add new members to teams
=> feat: Teams Page

ee/apps/command/package.json, ee/apps/command/pages/index.vue, ee/apps/command/pages/password-reset.vue, ee/apps/command/server/trpc/routers/accountRouter.ts, pnpm-lock.yaml
Reset Password/2FA function for command app
=> feat: Reset Password/2FA function for command app

apps/mail-bridge/postal-routes/inbound.ts
=> fix: Handle special characters in file names

apps/web/package.json, apps/web/src/app/[orgShortCode]/settings/org/mail/domains/[domainId]/page.tsx, apps/web/src/app/[orgShortCode]/settings/org/mail/domains/_components/add-domain-modal.tsx, apps/web/src/app/[orgShortCode]/settings/org/mail/domains/_components/columns.tsx, apps/web/src/app/[orgShortCode]/settings/org/mail/domains/page.tsx, apps/web/src/components/shadcn-ui/accordion.tsx, apps/web/tailwind.config.ts, pnpm-lock.yaml
Domains Page, New Domain Modal and Domain DNS records viewer.
=> feat: Domains Page with new domain modal and DNS records viewer

apps/web/src/app/[orgShortCode]/settings/org/mail/addresses/[addressId]/page.tsx, apps/web/src/app/[orgShortCode]/settings/org/mail/addresses/_components/add-address-modal.tsx, apps/web/src/app/[orgShortCode]/settings/org/mail/addresses/_components/columns.tsx, apps/web/src/app/[orgShortCode]/settings/org/mail/addresses/external/page.tsx, apps/web/src/app/[orgShortCode]/settings/org/mail/addresses/page.tsx, apps/web/src/components/shadcn-ui/alert.tsx
Added Email Addresses page, with new internal email modal, external email page and readonly settings per each email
=> feat: add email addresses page

apps/web/src/app/[orgShortCode]/convo/[convoId]/_components/messages-panel.tsx, apps/web/src/app/[orgShortCode]/convo/[convoId]/_components/original-message-view.tsx, apps/web/src/app/[orgShortCode]/convo/[convoId]/_components/participants.tsx, apps/web/src/components/shadcn-ui/scroll-area.tsx
Original Email headers and html view for emails with raw html
=> feat: Original email header and html view

apps/web/src/app/[orgShortCode]/_components/claim-email-identity.tsx, apps/web/src/app/[orgShortCode]/layout.tsx
=> feat: Show claim address modal when no identity is associated

apps/web/src/app/[orgShortCode]/convo/[convoId]/_components/messages-panel.tsx, apps/web/src/app/[orgShortCode]/convo/layout.tsx, apps/web/src/app/[orgShortCode]/convo/utils.ts, apps/web/src/providers/realtime-provider.tsx
Realtime system for getting new convos, updating convo entries, toggling convos and delting convos work now
=> feat: hook up realtime system to use proper functions

.vscode/cspell.json, apps/mail-bridge/app.ts, apps/mail-bridge/ctx.ts, apps/mail-bridge/package.json, apps/mail-bridge/postal-routes/inbound.ts, apps/mail-bridge/postal-routes/signature-middleware.ts, apps/mail-bridge/tracing.ts, apps/mail-bridge/trpc/trpc.ts, apps/platform/app.ts, apps/platform/ctx.ts, apps/platform/middlewares.ts, apps/platform/package.json, apps/platform/tracing.ts, apps/platform/trpc/trpc.ts, apps/storage/app.ts, apps/storage/ctx.ts, apps/storage/middlewares.ts, apps/storage/package.json, apps/storage/storage.ts, apps/storage/tracing.ts, packages/otel/env.ts, packages/otel/hono.ts, packages/otel/logger.ts, packages/otel/otel.ts, packages/otel/package.json, packages/otel/tsconfig.json, pnpm-lock.yaml
~Work In Progress PR for Open Telemtery~
~Uses Zipkin for now, still need to decide stuff~
Sets up basic tracing for Open Telemetry
=> feat: Introduce Open Telemetry

apps/mail-bridge/package.json, apps/mail-bridge/queue/mail-processor/worker.ts, apps/mail-bridge/utils/purify.ts, packages/database/migrations/0006_steep_karma.sql, packages/database/migrations/meta/0006_snapshot.json, packages/database/schema.ts, pnpm-lock.yaml
Save the minimally stripped and sanitized html version of emails for showing in UI incase of formatted emails
=> feat: Start saving original sanitized email in db

apps/mail-bridge/queue/mail-processor/worker.ts
> **Needs more testing on mailbridge**
Fixes #347
Fixes #493
=> fix: Handle when multiple emails are specified in `In-Reply-To` header

apps/web/src/app/[orgShortCode]/convo/[convoId]/_components/participants.tsx, apps/web/src/app/[orgShortCode]/convo/_components/convo-list-item.tsx, apps/web/src/app/[orgShortCode]/convo/layout.tsx
some small design changes to "assigned participant" and active convo
=> minor-design-cleanup

apps/mail-bridge/app.ts, apps/platform/app.ts, apps/storage/app.ts, ee/apps/billing/app.ts
The servers crashes on uncaught errors right now, even tho railway restarts them, its not the best thing. 
So currently we are catching the random errors to prevent the crashes.
=> fix: Stop crashing the servers on random errors

apps/mail-bridge/app.ts, apps/mail-bridge/env.ts, apps/mail-bridge/queue/mail-processor/index.ts, apps/mail-bridge/queue/mail-processor/worker.ts
Based on Linear issue `ENG-3`
mail-bridge will look for a `MAILBRIDGE_MODE` variable and works as a Handler or Worker or both depending on the needs. It allows us to scale the server efficently.
=> feat: Setup mail-bridge to have handler/worker/dual mode based on env var

packages/utils/discord.ts, packages/utils/package.json, pnpm-lock.yaml
Adds a discord webhook based logger for notifying the staff.
Provides `info`, `alert`, `critical` and `custom` embeded loggers.
it logs into console if `UTILS_LOGGING_DISCORD_WEBHOOK` is not set/invalid.
=> feat: create discord webhook logger

apps/mail-bridge/env.ts, apps/mail-bridge/queue/mail-processor/index.ts, apps/mail-bridge/queue/mail-processor/worker.ts
Setup Queue to store completed jobs for specified amount of time.
Also setup discord alerts on failed jobs.
=> feat: mailbridge queue job max age and discord alert setup

apps/platform/trpc/routers/contactRouter/contactRouter.ts, apps/web/src/app/[orgShortCode]/convo/_components/create-convo-form.tsx, apps/web/src/components/avatar.tsx
adds styling to new convo
Fixes #511
=> new-convo-styling

apps/web/src/app/[orgShortCode]/settings/user/addresses/_components/columns.tsx, apps/web/src/app/[orgShortCode]/settings/user/addresses/page.tsx, apps/web/src/components/copy-button.tsx, apps/web/src/components/shadcn-ui/card.tsx, apps/web/src/components/shadcn-ui/scroll-area.tsx
=> settings-personal-addresses

apps/web/src/app/[orgShortCode]/settings/user/security/page.tsx
=> settings-personal-security

apps/web/src/app/[orgShortCode]/settings/org/page.tsx
=> settings-org-profile

apps/mail-bridge/utils/contactParsing.ts
New contacts were not being assinged the correct names due to a bug,
This change is going to be picked into Production
=> hotfix: fix new contacts having no name

README.md, apps/web/package.json, apps/web/src/app/[orgShortCode]/settings/org/setup/billing/_components/plans-table.tsx, apps/web/src/app/[orgShortCode]/settings/org/setup/billing/page.tsx, apps/web/src/app/[orgShortCode]/settings/user/profile/page.tsx, apps/web/src/components/shadcn-ui/tabs.tsx, pnpm-lock.yaml
=> settings-org-billing

apps/mail-bridge/app.ts, apps/platform/app.ts, apps/storage/app.ts, ee/apps/billing/app.ts
Hono apps now serve some useful info on `/` health enpoint.
=> chore: Better health endpoints

apps/mail-bridge/package.json, apps/platform/package.json, apps/worker/package.json, ee/apps/billing/package.json, pnpm-lock.yaml
Updates `@hono/trpc-server` to `v0.3.2` to make it stop complaining about trpc 11.
=> chore: update `@hono/trpc-server` to 0.3.2

apps/web/package.json, apps/web/src/app/[orgShortCode]/convo/_components/convo-list.tsx, pnpm-lock.yaml
For the convo list we were using tanstack virtual which was causing issues, this PR replaces that with Virtuoso to match with the convo messages view, fix some issues and simplify the code.
=> fix: replace convo list with Virtuoso component to fix bugs

apps/web/src/app/[orgShortCode]/_components/sidebar-content.tsx, apps/web/src/app/[orgShortCode]/convo/[convoId]/_components/messages-panel.tsx, apps/web/src/app/[orgShortCode]/convo/_components/create-convo-form.tsx, apps/web/src/app/[orgShortCode]/convo/_components/new-convo-sheet.tsx, apps/web/src/app/[orgShortCode]/settings/layout.tsx, apps/web/src/app/layout.tsx, apps/web/src/components/avatar.tsx
fixes #537
fixes #500
Also few extra z-index, scroll bar and tooltip fixes that are needed for this to work properly
=> fix: new email based participants are correctly added now

apps/platform/trpc/ratelimit.ts, apps/platform/trpc/routers/authRouter/passkeyRouter.ts, apps/platform/trpc/routers/authRouter/passwordRouter.ts, apps/platform/trpc/routers/authRouter/recoveryRouter.ts, apps/platform/trpc/routers/authRouter/signupRouter.ts, apps/platform/trpc/routers/authRouter/twoFactorRouter.ts, apps/platform/trpc/routers/orgRouter/users/invitesRouter.ts, apps/platform/trpc/trpc.ts
Rate limit system has been re written to be more extensible and usable with all trpc routes.
=> feat: rewrite ratelimit to be more extensible

apps/web/src/app/(login)/login/page.tsx, apps/web/src/app/[orgShortCode]/settings/user/security/_components/reset-modals.tsx, apps/web/src/app/[orgShortCode]/settings/user/security/_components/verification-modal.tsx, apps/web/src/app/join/secure/_components/modals.tsx, apps/web/src/app/recovery/_components/modals.tsx, apps/web/src/components/password-input.tsx, apps/web/src/components/toggle-password.tsx
Show password button fix, input uncontrolled state fix, suggestion autofill fix
Fixes #461 
Show password button fix:
Before:
After:
input uncontrolled state fix, suggestion autofill fix:
Before:
https://github.com/un/inbox/assets/60394241/d6ae9363-632e-4115-a6c7-3e896bdbd0ad
After:
https://github.com/un/inbox/assets/60394241/68a551cd-e079-4f69-a0f5-694fdbeeb0f7
=> fix: password auto complete suggestion fix

apps/platform/trpc/routers/orgRouter/mail/domainsRouter.ts, apps/web/src/app/[orgShortCode]/settings/org/mail/domains/[domainId]/page.tsx, packages/database/migrations/0008_sour_falcon.sql, packages/database/migrations/meta/0008_snapshot.json, packages/database/migrations/meta/_journal.json, packages/database/schema.ts
Domain's DNS checking, Verification and Auto disable algorithm has been changed as per the discussed flowchart.
Eraser DIagram: https://app.eraser.io/workspace/G2emeBc8hN4bBZjn9Tpr?origin=share
=> feat: change domain DNS flow to new planned flow

apps/mail-bridge/env.ts, apps/mail-bridge/postal-db/index.ts, apps/mail-bridge/trpc/routers/domainRouter.ts, apps/mail-bridge/trpc/routers/orgRouter.ts, apps/mail-bridge/trpc/routers/sendMailRouter.ts, apps/platform/env.ts
The name of the variable and the in code was mismatched
=> fix: rename the postal local mode env variable to be proper one

apps/web/src/app/[orgShortCode]/_components/sidebar-content.tsx, apps/web/src/app/[orgShortCode]/_components/sidebar.tsx, apps/web/src/app/[orgShortCode]/settings/org/users/teams/_components/new-team-modal.tsx, apps/web/src/components/avatar-plus.tsx, apps/web/src/components/shadcn-ui/dialog.tsx, apps/web/src/components/shadcn-ui/tooltip.tsx
Select z-index fix, model z-index is 500, so I changed the select to have 550.
Team Name Input box default length fix was changing with validation error change fixed.
Fixes #568
=> select z index fix and input box default length fix

apps/platform/trpc/routers/orgRouter/mail/domainsRouter.ts, apps/platform/trpc/routers/orgRouter/mail/emailIdentityRouter.ts, apps/platform/trpc/routers/orgRouter/setup/profileRouter.ts, apps/platform/trpc/routers/orgRouter/users/invitesRouter.ts, apps/platform/trpc/routers/orgRouter/users/teamsRouter.ts, apps/platform/trpc/trpc.ts
Created a procedure that checks if the user is and admin in the organization.
=> TRPC: Create new orgAdminProcedure

apps/web/src/app/join/profile/_components/profile-card.tsx
=> fix-redirect-when-already-in-org

apps/web/src/app/[orgShortcode]/_components/sidebar-content.tsx
Adds conditional border styling to dark, light, and system theme toggle items
fixes #577
=> feat-display-current-theme

apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/context-panel.tsx, apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/messages-panel.tsx, apps/web/src/app/[orgShortcode]/convo/_components/convo-list.tsx, apps/web/src/app/[orgShortcode]/convo/layout.tsx, apps/web/src/app/[orgShortcode]/settings/layout.tsx, apps/web/src/app/[orgShortcode]/settings/org/mail/addresses/[addressId]/page.tsx, apps/web/src/app/[orgShortcode]/settings/org/mail/addresses/page.tsx, apps/web/src/app/[orgShortcode]/settings/org/users/invites/page.tsx, apps/web/src/app/[orgShortcode]/settings/org/users/teams/_components/new-team-modal.tsx, apps/web/src/styles/globals.css
Fixes issues with scrollbars, overflowing and made it look good.
Improved many of the `Loading...` with a spinner attached.
Fixed the Breadcrumb nav link
=> chore: improve scrollbar, links and loading states

apps/platform/trpc/routers/orgRouter/setup/profileRouter.ts, apps/platform/trpc/routers/orgRouter/users/invitesRouter.ts, apps/platform/utils/mail/inviteTemplate.ts, apps/platform/utils/mail/transactional.ts
fixes invite issue where org name was not correct due to stale cache
also added dynamic appurl to links
=> Fix: invite org name + app url

apps/platform/trpc/routers/orgRouter/orgCrudRouter.ts, apps/web/src/app/join/org/_components/create-org.tsx
Improves org name validation and shortcode generation by adding support for hyphens, using debounced input, handling errors more effectively, and updating UI components accordingly.
- Updated regex for org name validation to allow hyphens.
- Implemented debounced input for org name to reduce unnecessary requests.
- Added hooks for better state management around shortcode generation.
- Improved error handling for shortcode generation process.
- Updated relevant components to reflect changes.
1. Navigate to the org creation form.
2. Try creating an org with various names including hyphens.
3. Observe the debounce effect and error messages if any.
4. Verify that the shortcode is generated correctly based on the org name input.
---
=> fix: use debounce while generating shortcode based on org name

apps/web/src/components/turnstile.tsx, apps/web/src/styles/globals.css
The Turnstile widget is now a floating widget at the bottom of screen.
=> feat: Make turnstile a floating widget

apps/web/src/app/[orgShortcode]/convo/_components/create-convo-form.tsx
Pressing Enter now adds the email to participants list.
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/pdcPzzwHY7gqQNDOL86j/5d74d6f4-616c-46f5-978c-e5c1f03795f8.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/pdcPzzwHY7gqQNDOL86j/5d74d6f4-616c-46f5-978c-e5c1f03795f8.mov">Screen Recording 2024-07-25 at 17.29.41.mov</video>
=> feat: pressing enter in new Convo form adds the email address to list

apps/web/src/app/[orgShortcode]/convo/_components/create-convo-form.tsx
Fixes #624 
Note:
The hover card only hows for those where a potential issue of overflow was there. This was done so that user acn kind of see all the relevanet details of that user, for any other user it will will simple. However I am open to suggestions if it requires modification.
https://github.com/user-attachments/assets/04bf4f4b-2b74-4a21-b426-c18eb71348af
=> style(create-convo-form): overflow fixes and hover info

apps/web/src/app/[orgShortcode]/_components/sidebar-content.tsx, apps/web/src/env.js
=> fix: web sidebar version linking

apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/convo-views.tsx, apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/reply-box.tsx, apps/web/src/app/[orgShortcode]/convo/_components/create-convo-form.tsx, apps/web/src/app/[orgShortcode]/convo/utils.ts
Fix some frontend caching issues while updating/deleting convos
fixes #625
=> fix: improve caching performance and data updater

apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/messages-panel.tsx, apps/web/src/app/[orgShortcode]/convo/_components/convo-list-item.tsx, apps/web/src/app/[orgShortcode]/convo/_components/create-convo-form.tsx, apps/web/src/app/[orgShortcode]/convo/layout.tsx, apps/web/src/app/[orgShortcode]/settings/org/mail/addresses/_components/add-address-modal.tsx, apps/web/src/app/[orgShortcode]/settings/org/mail/addresses/_components/add-external-email-modal.tsx, apps/web/src/components/shadcn-ui/context-menu.tsx, packages/tiptap/react/components/editor.tsx, prettier.config.cjs
This PR is meant to fix issues with Virtuoso message list scroll and flickering.
I also found that not having prettier plugins in correct order can break things, so I also had to fix that
=> fix: prettier plugin and virtuoso flickering issue

apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/messages-panel.tsx
Replace "Convo Message Actions" as per design.
Fixes # ENG-77
=> feat:Convo Message Actions new UI

apps/platform/storage.ts, apps/platform/trpc/routers/authRouter/recoveryRouter.ts, apps/platform/trpc/routers/userRouter/securityRouter.ts, apps/web/src/app/recovery/reset-password/request/page.tsx, apps/web/src/app/recovery/reset-password/verify/page.tsx
While verifying recovery code makes sure to match the username with the code
=> chore: verify username while recovering password

packages/realtime/server.ts
Catch log and re-throw pusher emit errors
=> fix: catch and log pusher errors for debugging

apps/mail-bridge/tsup.config.ts, apps/platform/tsup.config.ts, apps/storage/tsup.config.ts, apps/worker/tsup.config.ts
Fixes realtime issues by keeping variable names intact in build
=> fix: keep names in build system

apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/original-message-view.tsx
Added a visually hidden title and description for accessibility purposes to the Original Message View Dialog.
=> fix: add accessibility title to original message view dialog

apps/web/src/app/[orgShortcode]/settings/user/security/page.tsx
=> fix: enable 2FA opens wrong modal

apps/mail-bridge/env.ts, apps/platform/env.ts, packages/realtime/server.ts
Fix realtime issues on staging by making port optional
=> fix: make realtime server port optional

apps/web/src/env.ts, packages/realtime/client.ts
Should have been part of #642, forgot to add
=> fix: optional port for realtime (nextjs Part)

apps/web/src/app/[orgShortcode]/settings/org/setup/billing/_components/plans-table.tsx, apps/web/src/app/[orgShortcode]/settings/org/setup/billing/page.tsx
- Commented out the 'Basic' and 'Self Host' plans in the Pricing Table component.
- Updated the 'Enterprise' plan to have a 'Contact Sales' action label and added an external link handler.
- Ensured the payment link is only opened once in StripeWatcher component.
- Improved the user instructions within the StripeWatcher dialog.
- Added an effect to show/hide plans based on the user's current plan.
- Commented out the 'Basic' and 'Self Host' plans from the Pricing Table component.
- Updated the 'Enterprise' plan in the Pricing Table.
- Modified the StripeWatcher component to ensure the payment link is opened only once.
- Improved user instructions in the StripeWatcher dialog.
- Added a useEffect in the Billing page to conditionally show plans based on the user's plan.
1. Go to the billing …
=> fix-billing-plans

apps/web/src/app/[orgShortcode]/_components/bottom-nav.tsx, apps/web/src/app/[orgShortcode]/convo/_components/convo-list.tsx
Nav item darker outline on active and rename "convo" to "message" 
Describe the change
Leave instructions for testing
Describe the motivation/reason behind this change
---
Fixes # ENG-98
- [x ] Enhancement (small improvements)
=> feat:Nav item active outline

apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/reply-box.tsx, apps/web/src/app/[orgShortcode]/convo/_components/create-convo-form.tsx, apps/web/src/stores/draft-store.ts
Save drafts in localstore and load them in each convo and new convo form
=> feat: create convo draft store

apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/convo-views.tsx, apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/reply-box.tsx, apps/web/src/app/[orgShortcode]/convo/_components/create-convo-form.tsx, apps/web/src/app/[orgShortcode]/convo/new/page.tsx
Don't show email identity selector unless an external participant is added.
Allow users to send emails to internal participants without a email identity.
Fixes ENG-105
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/pdcPzzwHY7gqQNDOL86j/e7f66147-951f-4566-8f1f-5a6e78f38db3.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/pdcPzzwHY7gqQNDOL86j/e7f66147-951f-4566-8f1f-5a6e78f38db3.mov">Screen Recording 2024-08-07 at 12.04.54.mov</video>
=> fix: allow and don't show email identity without external participants

apps/web/src/app/[orgShortcode]/_components/bottom-nav.tsx, apps/web/src/app/[orgShortcode]/_components/sidebar-content.tsx, apps/web/src/app/[orgShortcode]/_components/sidebar.tsx, apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/convo-views.tsx, apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/top-bar.tsx, apps/web/src/app/[orgShortcode]/convo/[convoId]/page.tsx, apps/web/src/app/[orgShortcode]/convo/layout.tsx, apps/web/src/app/[orgShortcode]/convo/page.tsx, apps/web/src/app/[orgShortcode]/layout.tsx, apps/web/src/app/[orgShortcode]/settings/_components/page-title.tsx, apps/web/src/app/[orgShortcode]/settings/layout.tsx, apps/web/src/app/[orgShortcode]/settings/org/mail/addresses/page.tsx, apps/web/src/app/[orgShortcode]/settings/org/mail/domains/page.tsx, apps/web/src/app/[orgShortcode]/settings/org/page.tsx, apps/web/src/app/[orgShortcode]/settings/org/users/invites/page.tsx, apps/web/src/app/[orgShortcode]/settings/org/users/members/page.tsx, apps/web/src/app/[orgShortcode]/settings/org/users/teams/[teamId]/page.tsx, apps/web/src/app/[orgShortcode]/settings/org/users/teams/page.tsx, apps/web/src/app/[orgShortcode]/settings/page.tsx, apps/web/src/app/[orgShortcode]/settings/route.tsx, apps/web/src/app/[orgShortcode]/settings/user/security/page.tsx, apps/web/src/app/[orgShortcode]/tunnels.ts
This PR changes how we handle the mobile navigation.
It's a new component that is only visible when `useIsMobile` is true (when screen width is less than 768px).
there are 3 main components to the menu bar:
- Convo Button
This button will take the user directly to their list of conversations. When on the convo list page, this button is set to active state.
- New Convo Button
This button will navigate the user to the new convo page where it will be markes as active. Later we will change the functionality to open the new convo drawer instead of using the page.
- Menu
The menu button opens the `OrgSwitcher` menu from the main desktop sidebar.
This button is active when the menu is open (regardless of which page its on``
-- Additional changes
The menu is a dropdown menu and not a page. this …
=> fix-mobile-view

apps/web/src/app/[orgShortcode]/_components/sidebar-content.tsx
=> fix(web/mobile/menu): fix menu item

packages/database/schema.ts
Deleted in accountMetadata should be optional
=> fix: make deleted optional in AccountMetadata

apps/mail-bridge/package.json, apps/platform/package.json, apps/storage/package.json, apps/web/package.json, apps/worker/package.json
=> bump version

packages/database/migrations/0010_greedy_weapon_omega.sql, packages/database/migrations/meta/0010_snapshot.json, packages/database/migrations/meta/_journal.json, packages/database/schema.ts
=> fix-db-column-raw-emails

apps/mail-bridge/app.ts
Close open db connections as part of cleanup in mail-bridge.
Prevents these issues every time we deploy
=> fix: close open db connection with postal-db as cleanup

packages/database/migrations/0011_violet_red_shift.sql, packages/database/migrations/meta/0011_snapshot.json, packages/database/migrations/meta/_journal.json, packages/database/schema.ts
2nd db column with length issue
=> 2nd-fix-db-column-plain-email

apps/mail-bridge/queue/mail-processor.ts
Add extra info in emailIdentity Id not found error log to help us debug the errors.
=> fix: add extra info to the emailIdentityIds error

apps/web/src/app/[orgShortcode]/settings/page.tsx
fixes issue where mobile settings nav is not navigatable due to redirect bug
=> fix-mobile-settings

apps/platform/trpc/routers/authRouter/signupRouter.ts, apps/platform/utils/signup.ts
=> adjust-username-checks

apps/web/src/app/[orgShortcode]/convo/_components/convo-list-item.tsx
Added trimStart() to eliminate leading whitespace from convo message preview list. Couldn’t reproduce on my environment. please test on review. 
Modified convo-list-item.tsx to adjust convo message text rendering.
1. Retrieve a conversation with leading whitespace in the first message.
2. Verify that the whitespace is correctly trimmed from the displayed message.
Ensures a cleaner UI and prevents layout issues caused by unexpected leading whitespace in conversation messages.
---
Fixes #ENG-119
=> feat: UI fix remove whitespaces from messages list

apps/web/src/app/[orgShortcode]/settings/org/mail/addresses/_components/add-address-modal.tsx, apps/web/src/app/[orgShortcode]/settings/org/mail/addresses/_components/add-external-email-modal.tsx
Select teams properly when creating email address
Fixes ENG-123
=> fix: select teams properly in add email modal

apps/platform/trpc/routers/orgRouter/mail/domainsRouter.ts, apps/web/src/app/[orgShortcode]/settings/org/mail/domains/[domainId]/page.tsx, apps/web/src/app/[orgShortcode]/settings/org/mail/domains/_components/add-domain-modal.tsx, apps/web/src/app/[orgShortcode]/settings/org/mail/domains/_components/columns.tsx, ee/apps/billing/trpc/routers/iCanHazRouter.ts
Add support for disabling domains
Fixes ENG-110
=> feat: allow disabling domains

apps/mail-bridge/postal-db/functions.ts, apps/mail-bridge/trpc/routers/orgRouter.ts, apps/platform/trpc/routers/userRouter/securityRouter.ts
While deleting a org, delete the org from postal database too.
=> feat: delete orgs from postal db while deleting org in platform

apps/web/src/hooks/use-time-ago.ts
Fixes #663
https://github.com/user-attachments/assets/b319c44d-9a14-4679-bfed-fa1913e1245f
=> chore(useTimeAgo): set default language to en

apps/web/next.config.js
Enabling Production sourcemaps would make it easier to debug random crashes in browser
=> chore: enable production source maps

ee/apps/command/src/middleware.ts
Fixes the URL to properly redirect from command
=> fix: command to app redirect

apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/messages-panel.tsx
Fix for this issue I missed somehow, glad it didn't go out to production
=> fix: make shy regex global

apps/web/src/components/avatar-crop.tsx
=> feat: scale down avatars if they are too big after cropping

apps/web/src/app/[orgShortcode]/_components/sidebar-content.tsx
Fixes #688
https://github.com/user-attachments/assets/460db963-df88-4f10-8aef-b927c8e312f2
=> style(sidebar-content): truncate organisation name

apps/web/src/components/editor/index.tsx, apps/web/src/components/editor/selectors.tsx, apps/web/tailwind.config.ts
Fixes #698
I have also added custom plugin so that on hovering over editor links it would show different cursor.
=> fix(tiptap-editor): delete link from editor

apps/web/src/app/[orgShortcode]/_components/sidebar-content.tsx
=> fix: squished avatar

apps/platform/trpc/routers/userRouter/profileRouter.ts, apps/web/src/app/[orgShortcode]/settings/user/profile/page.tsx
Fixes #703
https://www.loom.com/share/61d70aff1fea407d84c4fb267582985d?sid=ba76c45e-6e55-4891-8d06-8f13381c0fd9
=> fix:(user-profile): profile split name and validations

apps/mail-bridge/package.json, apps/platform/package.json, apps/storage/package.json, apps/v1Migration/package.json, apps/web/package.json, apps/worker/package.json, ee/apps/command/package.json, package.json, packages/eslint-plugin/package.json, packages/hono/package.json, packages/otel/package.json, packages/realtime/package.json, packages/tiptap/package.json
=> feat: version 1.0.0 bump

apps/web/src/app/[orgShortcode]/_components/bottom-nav.tsx, apps/web/src/app/[orgShortcode]/_components/sidebar-content.tsx
=> fix-mobile-spaces-nav

apps/web/src/app/(login)/page.tsx
Login screen minor fixes
Fixes #718
=> fix: login screen minor fixes

apps/web/src/app/[orgShortcode]/_components/sidebar-content.tsx
Show actual space name instead of personal space
If the default value is present, it shows the same
Fixes #720
=> Show actual space name instead of personal space

apps/mail-bridge/postal-routes/inbound.ts, apps/mail-bridge/queue/mail-processor.ts, apps/worker/app.ts, apps/worker/services/dns-check-queue.ts, packages/utils/discord.ts
Removes the debug console log and other debugging stuff
Also Fixes ENG-134
=> chore: cleanup console logs and other stuff

apps/web/src/app/[orgShortcode]/[spaceShortcode]/convo/welcome/_components/top-bar.tsx, apps/web/src/app/[orgShortcode]/[spaceShortcode]/convo/welcome/_components/welcome-message.tsx, apps/web/src/app/[orgShortcode]/[spaceShortcode]/convo/welcome/_components/welcome-messages.tsx, apps/web/src/app/[orgShortcode]/[spaceShortcode]/convo/welcome/_data/welcomeMessages.tsx, apps/web/src/app/[orgShortcode]/[spaceShortcode]/convo/welcome/page.tsx, apps/web/src/app/[orgShortcode]/convo/_components/convo-list-base.tsx, apps/web/src/app/[orgShortcode]/convo/layout.tsx
This PR introduces a new "Welcome" feature for new users in the UnInbox application. Here's a summary of the changes:
1. New Welcome Components:
- Added `TopBar`, `WelcomeMessage`, and `WelcomeMessages` components.
- These components create a structured welcome experience for new users.
2. Welcome Messages:
- Created a set of welcome messages in `welcomeMessages.tsx`.
- Messages introduce users to UnInbox features and guide them through initial setup.
3. Welcome Page:
- Added a new `WelcomePage` component that displays welcome messages sequentially.
- Includes links to important settings and resources.
4. ConvoList Updates:
- Modified `ConvoListBase` to include a link to the welcome page when the conversation list is empty.
- This provides a better onboarding experience for new users.
5. …
=> Basic onboarding

apps/web/src/app/[orgShortcode]/[spaceShortcode]/settings/page.tsx
Fixes #729
Please check the discord discussion before merging this pr: https://discord.com/channels/1113119653246545961/1276274816847970438
=> fix: Description Field Label

apps/web/package.json, apps/web/src/app/[orgShortcode]/convo/utils.ts, apps/web/src/lib/trpc.tsx, pnpm-lock.yaml
Update convo list at proper position when adding new convos
=> fix: convo position while adding new convo

apps/web/src/app/[orgShortcode]/settings/org/page.tsx
Fixes `[Bug] Org name not changing instantly` issue.
https://github.com/user-attachments/assets/dde49cf3-0cfc-4b18-9852-19837689ef40
=> [Bug fix] Org name not changing instantly

apps/web/src/app/[orgShortcode]/convo/[convoId]/_components/original-message-view.tsx
Original Message view uses collapsible accordion now
=> feat: original message view with accordion

apps/mail-bridge/postal-db/functions.ts, apps/platform/utils/updateDnsRecords.ts, apps/worker/functions/check-dns.ts, apps/worker/services/dns-check-queue.ts
Attach extra info using OpenTelemetry to DNS checking functions to debug the random DNS issues
=> chore: instrument dns check functions

apps/mail-bridge/queue/mail-processor.ts
While finding the parent convo, use all message ids found in `In-Reply-To` and `References` header to determine any matching entries
Fixes ENG-168
=> fix: use all `In-Reply-To` and `References` to find related messages

apps/platform/trpc/routers/orgRouter/orgCrudRouter.ts, apps/platform/trpc/routers/orgRouter/setup/profileRouter.ts, apps/platform/trpc/routers/userRouter/securityRouter.ts, apps/web/src/app/[orgShortcode]/settings/org/page.tsx
Allow org owners to delete orgs
Fixed ENG-115
Fixes ENG-106
=> feat: allow option to delete orgs

apps/platform/trpc/routers/orgRouter/mail/emailIdentityRouter.ts, apps/web/src/app/[orgShortcode]/settings/org/mail/addresses/[addressId]/page.tsx, apps/web/src/components/avatar.tsx
Options to 
- Edit send name
- Add/Remove Senders
- Add/Remove Destinations
Fixes ENG-159
=> feat: options to edit email send name, senders and destinations

.vscode/settings.json, apps/web/src/app/[orgShortcode]/convo/_components/convo-list-item.tsx, package.json, pnpm-lock.yaml
Finally getting rid of `@radix-ui/*` and other auto imports
=> chore: exclude auto imports

package.json, predev.ts
Check for correct node version and env file before running the dev command
=> chore: add predev script to check node version and env file

ee/apps/billing/trpc/routers/stripeLinksRouter.ts
Fix return url for billing portal
=> fix: correct billing return url
